In [25]:
import tensorflow as tf
from numpy.random import RandomState
#### 1. 定义神经网络的参数，输入和输出节点。
batch_size = 8
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))


x = tf.placeholder(tf.float32, shape=(None, 2), name='x-input')
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')



#### 2. 定义前向传播过程，损失函数及反向传播算法。"
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

####  3. 生成模拟数据集。
rdm = RandomState(1)
X = rdm.rand(128,2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

#### 4. 创建一个会话来运行TensorFlow程序。
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print ("w1:", sess.run(w1))
    print ("w2:", sess.run(w2))
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))

        # 输出训练后的参数取值。
        print("\n")
        print("w1:", sess.run(w1))
        print("w2:", sess.run(w2))

w1: [[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
w2: [[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
After 0 training step(s), cross entropy on all data is 0.0674925


w1: [[-0.8123182   1.4855988   0.06632921]
 [-2.4437041   0.1002484   0.59222424]]
w2: [[-0.8123182 ]
 [ 1.4855988 ]
 [ 0.06632937]]


w1: [[-0.8132937   1.4865743   0.06730329]
 [-2.4446583   0.1012025   0.59318024]]
w2: [[-0.8132974 ]
 [ 1.4865836 ]
 [ 0.06729427]]


w1: [[-0.81404775  1.4873284   0.06805624]
 [-2.445396    0.10194003  0.5939192 ]]
w2: [[-0.8140543 ]
 [ 1.4873449 ]
 [ 0.06804014]]


w1: [[-0.81466544  1.4879462   0.06867302]
 [-2.446       0.10254417  0.59452456]]
w2: [[-0.8146743 ]
 [ 1.4879684 ]
 [ 0.06865111]]


w1: [[-0.8151875   1.4884683   0.06919434]
 [-2.4465108   0.1030548   0.5950362 ]]
w2: [[-0.81519836]
 [ 1.4884955 ]
 [ 0.06916752]]


w1: [[-0.81563747  1.4889183   0.06964365]
 [-2.446951    0.1034949   0.59547716]]
w2: [[-0.81565005]
 [ 1.4889498 ]
 [ 0.069



w1: [[-0.9107965   1.5831419   0.18104485]
 [-2.5369549   0.19257645  0.70144   ]]
w2: [[-0.90910953]
 [ 1.5865363 ]
 [ 0.16498613]]


w1: [[-0.9113653   1.5836983   0.1818015 ]
 [-2.537555    0.19316372  0.702231  ]]
w2: [[-0.90971214]
 [ 1.5871336 ]
 [ 0.16563994]]


w1: [[-0.9119472   1.5842673   0.18257757]
 [-2.538187    0.19378197  0.70306563]]
w2: [[-0.9103431 ]
 [ 1.5877478 ]
 [ 0.16632612]]


w1: [[-0.9125339   1.5848409   0.18336178]
 [-2.5388534   0.19443364  0.70394695]]
w2: [[-0.9110029]
 [ 1.5883719]
 [ 0.1670457]]


w1: [[-0.91322434  1.5855157   0.18428403]
 [-2.539468    0.19503479  0.70476043]]
w2: [[-0.91164106]
 [ 1.5890789 ]
 [ 0.1677344 ]]


w1: [[-0.9138479   1.5861253   0.18511693]
 [-2.540023    0.1955777   0.7054951 ]]
w2: [[-0.9122174 ]
 [ 1.5897175 ]
 [ 0.16835637]]


w1: [[-0.9144235   1.5866879   0.18588626]
 [-2.5406585   0.196199    0.7063378 ]]
w2: [[-0.9128504 ]
 [ 1.5903276 ]
 [ 0.16904695]]


w1: [[-0.9150558   1.5873058   0.18673313]
 [-2.5412865 



w1: [[-0.9909586   1.6607599   0.29456306]
 [-2.6210768   0.27416658  0.8174724 ]]
w2: [[-0.9928265 ]
 [ 1.6715637 ]
 [ 0.25973868]]


w1: [[-0.9914142   1.6611966   0.29524034]
 [-2.621628    0.27469674  0.81825453]]
w2: [[-0.9933562 ]
 [ 1.6720678 ]
 [ 0.26036236]]


w1: [[-0.9918914   1.6616538   0.29595065]
 [-2.6222231   0.275269    0.81909937]]
w2: [[-0.99392515]
 [ 1.6725997 ]
 [ 0.2610328 ]]


w1: [[-0.99250346  1.6622401   0.29685885]
 [-2.6227732   0.27579796  0.81988055]]
w2: [[-0.99448353]
 [ 1.6732343 ]
 [ 0.2616896 ]]


w1: [[-0.99305534  1.6627688   0.29767776]
 [-2.623269    0.27627492  0.82058495]]
w2: [[-0.994987  ]
 [ 1.6738067 ]
 [ 0.26228184]]


w1: [[-0.9935662   1.6632583   0.29843608]
 [-2.6238523   0.27683556  0.8214135 ]]
w2: [[-0.99555296]
 [ 1.6743646 ]
 [ 0.2629491 ]]


w1: [[-0.99402684  1.6636996   0.2991198 ]
 [-2.624378    0.27734107  0.8221606 ]]
w2: [[-0.99606323]
 [ 1.6748676 ]
 [ 0.26355076]]


w1: [[-0.99444216  1.6640975   0.2997363 ]
 [-2.62485



w1: [[-1.070725    1.7368802   0.41387403]
 [-2.6895235   0.3396597   0.91749513]]
w2: [[-1.0626558]
 [ 1.7540052]
 [ 0.3447905]]


w1: [[-1.0712458   1.7373765   0.41465256]
 [-2.6898577   0.33997816  0.91800284]]
w2: [[-1.0630217]
 [ 1.7545192]
 [ 0.3452567]]


w1: [[-1.0717151   1.7378237   0.41535413]
 [-2.690159    0.34026515  0.91846037]]
w2: [[-1.0633513]
 [ 1.7549825]
 [ 0.3456768]]


w1: [[-1.0721381   1.7382268   0.4159864 ]
 [-2.6904306   0.34052378  0.9188727 ]]
w2: [[-1.0636483 ]
 [ 1.7554    ]
 [ 0.34605542]]


w1: [[-1.0725193   1.73859     0.41655615]
 [-2.6906753   0.34075686  0.9192443 ]]
w2: [[-1.0639161]
 [ 1.7557762]
 [ 0.3463966]]


w1: [[-1.0728629   1.7389174   0.4170696 ]
 [-2.6908958   0.3409669   0.91957915]]
w2: [[-1.0641574 ]
 [ 1.7561152 ]
 [ 0.34670407]]


w1: [[-1.0732715   1.7393067   0.41768128]
 [-2.6911783   0.34123594  0.92000943]]
w2: [[-1.06446   ]
 [ 1.7565236 ]
 [ 0.34708983]]


w1: [[-1.0737168   1.739731    0.41834834]
 [-2.6915329   0.34157

w2: [[-1.1129668 ]
 [ 1.8208224 ]
 [ 0.41066584]]


w1: [[-1.1373488   1.80034     0.51364195]
 [-2.7372985   0.3850641   0.991944  ]]
w2: [[-1.1133479]
 [ 1.8212652]
 [ 0.4111739]]


w1: [[-1.1379217   1.8008864   0.514496  ]
 [-2.7376604   0.38540742  0.9925239 ]]
w2: [[-1.1137463 ]
 [ 1.821833  ]
 [ 0.41171432]]


w1: [[-1.1384379   1.8013786   0.5152655 ]
 [-2.7379863   0.38571674  0.99304634]]
w2: [[-1.1141052]
 [ 1.8223445]
 [ 0.4122012]]


w1: [[-1.1389029   1.8018221   0.5159588 ]
 [-2.73828     0.38599542  0.99351704]]
w2: [[-1.1144285 ]
 [ 1.8228054 ]
 [ 0.41263986]]


w1: [[-1.1393219   1.8022215   0.5165834 ]
 [-2.7385447   0.3862465   0.99394107]]
w2: [[-1.1147199 ]
 [ 1.8232206 ]
 [ 0.41303506]]


w1: [[-1.1396995   1.8025814   0.5171461 ]
 [-2.7387831   0.3864727   0.99432313]]
w2: [[-1.1149824]
 [ 1.8235947]
 [ 0.4133911]]


w1: [[-1.1400396   1.8029057   0.5176531 ]
 [-2.738998    0.3866765   0.99466735]]
w2: [[-1.1152188]
 [ 1.8239317]
 [ 0.4137119]]


w1: [[-1.140345


w1: [[-1.1964937   1.8568107   0.60147995]
 [-2.774979    0.42079765  1.0533733 ]]
w2: [[-1.1547712 ]
 [ 1.8800894 ]
 [ 0.46850112]]


w1: [[-1.1969366   1.857234    0.60213536]
 [-2.7752175   0.4210237   1.0537684 ]]
w2: [[-1.1550494 ]
 [ 1.8805192 ]
 [ 0.46889824]]


w1: [[-1.1973355   1.8576154   0.60272574]
 [-2.7754323   0.42122734  1.0541242 ]]
w2: [[-1.1553    ]
 [ 1.8809062 ]
 [ 0.46925598]]


w1: [[-1.1976949   1.8579589   0.6032576 ]
 [-2.775626    0.42141077  1.0544448 ]]
w2: [[-1.1555258 ]
 [ 1.8812549 ]
 [ 0.46957824]]


w1: [[-1.1980187   1.8582684   0.6037367 ]
 [-2.7758002   0.42157602  1.0547335 ]]
w2: [[-1.1557292]
 [ 1.881569 ]
 [ 0.4698685]]


w1: [[-1.1983103  1.8585471  0.6041683]
 [-2.7759573  0.4217249  1.0549936]]
w2: [[-1.1559124]
 [ 1.881852 ]
 [ 0.47013  ]]


w1: [[-1.198573    1.8587981   0.60455704]
 [-2.7760987   0.42185897  1.055228  ]]
w2: [[-1.1560774 ]
 [ 1.8821069 ]
 [ 0.47036555]]


w1: [[-1.1989151   1.8591253   0.60506403]
 [-2.7763245   0.422072

w2: [[-1.2006239 ]
 [ 1.9438299 ]
 [ 0.53421855]]


w1: [[-1.2603365   1.917885    0.69582194]
 [-2.8174253   0.4609945   1.1245492 ]]
w2: [[-1.2009145]
 [ 1.9442685]
 [ 0.5346476]]


w1: [[-1.2607403   1.9182713   0.69641757]
 [-2.817652    0.46120906  1.1249335 ]]
w2: [[-1.2011763 ]
 [ 1.9446635 ]
 [ 0.53503406]]


w1: [[-1.261104   1.9186194  0.6969541]
 [-2.8178563  0.4614023  1.1252797]]
w2: [[-1.2014121 ]
 [ 1.9450194 ]
 [ 0.53538215]]


w1: [[-1.2614316   1.9189329   0.6974373 ]
 [-2.8180404   0.46157637  1.1255914 ]]
w2: [[-1.2016245]
 [ 1.9453399]
 [ 0.5356957]]


w1: [[-1.2617266   1.9192153   0.6978726 ]
 [-2.818206    0.46173316  1.1258723 ]]
w2: [[-1.2018158]
 [ 1.9456286]
 [ 0.5359781]]


w1: [[-1.2619923   1.9194697   0.69826466]
 [-2.8183553   0.4618744   1.1261252 ]]
w2: [[-1.2019882]
 [ 1.9458886]
 [ 0.5362325]]


w1: [[-1.2623385   1.919801    0.69877595]
 [-2.8185935   0.46209967  1.1265296 ]]
w2: [[-1.2022444 ]
 [ 1.9462391 ]
 [ 0.53660536]]


w1: [[-1.2627333  1.9

w1: [[-1.3124084  1.9676958  0.7728979]
 [-2.859977   0.5012034  1.1970247]]
w2: [[-1.2442727 ]
 [ 1.9988401 ]
 [ 0.59759545]]


w1: [[-1.3126147  1.9678926  0.7732062]
 [-2.8602166  0.5014294  1.1974329]]
w2: [[-1.2444948 ]
 [ 1.9990757 ]
 [ 0.59791297]]


w1: [[-1.3128004   1.9680699   0.7734838 ]
 [-2.8604324   0.50163287  1.1978005 ]]
w2: [[-1.2446948 ]
 [ 1.9992878 ]
 [ 0.59819895]]


w1: [[-1.3131365  1.9683905  0.7739862]
 [-2.8606846  0.5018708  1.1982309]]
w2: [[-1.2449579]
 [ 1.9996331]
 [ 0.5985872]]


w1: [[-1.3134391   1.9686792   0.77443874]
 [-2.8609118   0.5020851   1.1986184 ]]
w2: [[-1.2451948]
 [ 1.9999441]
 [ 0.5989369]]


w1: [[-1.3137116  1.9689392  0.7748463]
 [-2.8611166  0.5022781  1.1989675]]
w2: [[-1.2454082]
 [ 2.000224 ]
 [ 0.5992519]]


w1: [[-1.3139571  1.9691734  0.7752134]
 [-2.861301   0.5024519  1.1992818]]
w2: [[-1.2456003 ]
 [ 2.0004764 ]
 [ 0.59953564]]


w1: [[-1.3141782   1.9693844   0.77554405]
 [-2.8614671   0.5026085   1.1995649 ]]
w2: [[-1.24



w1: [[-1.3515065   2.0049405   0.831625  ]
 [-2.8936126   0.53285813  1.2544756 ]]
w2: [[-1.2778429 ]
 [ 2.0401738 ]
 [ 0.64697266]]


w1: [[-1.3517603   2.005182    0.83200717]
 [-2.8938138   0.5330472   1.2548195 ]]
w2: [[-1.2780482 ]
 [ 2.040437  ]
 [ 0.64727837]]


w1: [[-1.3520691   2.0054758   0.83247226]
 [-2.894141    0.5333545   1.2553775 ]]
w2: [[-1.278356 ]
 [ 2.0407808]
 [ 0.6477267]]


w1: [[-1.3523473   2.0057404   0.8328911 ]
 [-2.8944354   0.53363127  1.2558801 ]]
w2: [[-1.2786332]
 [ 2.0410903]
 [ 0.6481305]]


w1: [[-1.3525977   2.0059786   0.83326834]
 [-2.8947008   0.53388053  1.2563328 ]]
w2: [[-1.2788829]
 [ 2.041369 ]
 [ 0.6484941]]


w1: [[-1.3528234  2.0061932  0.8336081]
 [-2.8949397  0.534105   1.2567405]]
w2: [[-1.2791077 ]
 [ 2.04162   ]
 [ 0.64882165]]


w1: [[-1.3530265   2.0063865   0.83391404]
 [-2.8951547   0.5343072   1.2571076 ]]
w2: [[-1.2793102 ]
 [ 2.041846  ]
 [ 0.64911664]]


w1: [[-1.3532095  2.0065606  0.8341896]
 [-2.8953485  0.5344893  1.2

 [-2.9290488  0.5661118  1.3148344]]
w2: [[-1.3128802]
 [ 2.083091 ]
 [ 0.6989526]]


w1: [[-1.3923475  2.0437481  0.8931625]
 [-2.929263   0.5663127  1.3151985]]
w2: [[-1.3131121]
 [ 2.0834155]
 [ 0.6993064]]


w1: [[-1.3926412   2.0440269   0.89360493]
 [-2.9294562   0.5664936   1.3155265 ]]
w2: [[-1.3133211]
 [ 2.0837076]
 [ 0.699625 ]]


w1: [[-1.3929057  2.044278   0.8940034]
 [-2.92963    0.5666565  1.3158219]]
w2: [[-1.3135092 ]
 [ 2.0839708 ]
 [ 0.69991195]]


w1: [[-1.3931439  2.044504   0.8943622]
 [-2.9297867  0.5668032  1.316088 ]]
w2: [[-1.3136786 ]
 [ 2.0842078 ]
 [ 0.70017034]]


w1: [[-1.3933583   2.0447075   0.8946854 ]
 [-2.9299276   0.56693536  1.3163276 ]]
w2: [[-1.3138312 ]
 [ 2.0844212 ]
 [ 0.70040303]]


w1: [[-1.3935516   2.0448909   0.89497644]
 [-2.9300547   0.5670544   1.3165433 ]]
w2: [[-1.3139687]
 [ 2.0846133]
 [ 0.7006126]]


w1: [[-1.393847   2.0451713  0.8954215]
 [-2.9302912  0.5672759  1.3169452]]
w2: [[-1.3142081 ]
 [ 2.0849195 ]
 [ 0.70097214]]


w1

w1: [[-1.4326901  2.0819986  0.9538825]
 [-2.9644587  0.5992602  1.3747345]]
w2: [[-1.3478031]
 [ 2.126041 ]
 [ 0.7511246]]


w1: [[-1.4329643  2.0822582  0.9542943]
 [-2.9646404  0.5994301  1.3750407]]
w2: [[-1.3479989]
 [ 2.1263132]
 [ 0.7514245]]


w1: [[-1.4332112  2.082492   0.9546652]
 [-2.964804   0.5995831  1.3753164]]
w2: [[-1.348175  ]
 [ 2.1265583 ]
 [ 0.75169456]]


w1: [[-1.4334335  2.0827026  0.9549992]
 [-2.9649513  0.5997209  1.3755647]]
w2: [[-1.3483337 ]
 [ 2.126779  ]
 [ 0.75193775]]


w1: [[-1.4336338  2.0828922  0.9553   ]
 [-2.965084   0.599845   1.3757883]]
w2: [[-1.3484766 ]
 [ 2.126978  ]
 [ 0.75215673]]


w1: [[-1.4339398   2.083182    0.9557597 ]
 [-2.965331    0.60007596  1.3762046 ]]
w2: [[-1.3487256]
 [ 2.127295 ]
 [ 0.7525319]]


w1: [[-1.4342154  2.0834432  0.9561737]
 [-2.9655535  0.6002839  1.3765795]]
w2: [[-1.3489497]
 [ 2.1275804]
 [ 0.7528697]]


w1: [[-1.4345504  2.0837605  0.956677 ]
 [-2.9659147  0.6006216  1.377187 ]]
w2: [[-1.3492846 ]
 [ 2.12

w1: [[-1.4686767   2.1160972   1.0076815 ]
 [-2.9882722   0.62151754  1.4149176 ]]
w2: [[-1.3734735]
 [ 2.1617532]
 [ 0.7905812]]


w1: [[-1.4688504   2.116262    1.0079393 ]
 [-2.988399    0.62163603  1.4151319 ]]
w2: [[-1.3736056 ]
 [ 2.1619291 ]
 [ 0.79078287]]


w1: [[-1.4690068  2.1164103  1.0081716]
 [-2.9885132  0.6217428  1.4153249]]
w2: [[-1.3737246]
 [ 2.1620874]
 [ 0.7909644]]


w1: [[-1.4691476  2.1165438  1.0083807]
 [-2.988616   0.6218389  1.4154987]]
w2: [[-1.3738316]
 [ 2.16223  ]
 [ 0.7911279]]


w1: [[-1.4692744  2.1166642  1.008569 ]
 [-2.9887085  0.6219255  1.4156553]]
w2: [[-1.3739281]
 [ 2.1623585]
 [ 0.7912752]]


w1: [[-1.4693886   2.1167724   1.0087385 ]
 [-2.988792    0.62200344  1.4157963 ]]
w2: [[-1.374015 ]
 [ 2.1624742]
 [ 0.7914078]]


w1: [[-1.469694   2.117062   1.0091914]
 [-2.9889402  0.622142   1.416047 ]]
w2: [[-1.3741963]
 [ 2.1627612]
 [ 0.7916953]]


w1: [[-1.469969    2.117323    1.0095992 ]
 [-2.9890738   0.62226677  1.4162728 ]]
w2: [[-1.37435

 [ 0.82915574]]


w1: [[-1.5048014  2.1503944  1.0608982]
 [-3.0110161  0.6427772  1.4533838]]
w2: [[-1.3984989]
 [ 2.1972451]
 [ 0.8293552]]


w1: [[-1.504989    2.1505728   1.0611725 ]
 [-3.011109    0.64286417  1.4535412 ]]
w2: [[-1.3986121 ]
 [ 2.197422  ]
 [ 0.82953477]]


w1: [[-1.5052944  2.150863   1.0616189]
 [-3.0113373  0.6430775  1.4539269]]
w2: [[-1.3988482]
 [ 2.1977327]
 [ 0.829895 ]]


w1: [[-1.5055695  2.1511242  1.0620209]
 [-3.0115428  0.6432696  1.4542744]]
w2: [[-1.3990607 ]
 [ 2.1980124 ]
 [ 0.83021945]]


w1: [[-1.505817    2.1513596   1.0623829 ]
 [-3.0117278   0.64344263  1.4545873 ]]
w2: [[-1.3992522]
 [ 2.1982641]
 [ 0.8305116]]


w1: [[-1.5060401   2.1515715   1.062709  ]
 [-3.0118945   0.64359844  1.4548692 ]]
w2: [[-1.3994246]
 [ 2.1984909]
 [ 0.8307747]]


w1: [[-1.506241    2.1517625   1.0630026 ]
 [-3.0120447   0.64373875  1.4551228 ]]
w2: [[-1.3995798 ]
 [ 2.1986952 ]
 [ 0.83101165]]


w1: [[-1.5064218  2.1519344  1.063267 ]
 [-3.0121799  0.6438651  1.



w1: [[-1.5399423   2.1838171   1.1119257 ]
 [-3.03376     0.66403973  1.4918009 ]]
w2: [[-1.4233203]
 [ 2.2319314]
 [ 0.8677489]]


w1: [[-1.5401573  2.184022   1.1122359]
 [-3.033869   0.6641416  1.4919847]]
w2: [[-1.4234523]
 [ 2.2321348]
 [ 0.8679579]]


w1: [[-1.540351   2.1842062  1.1125152]
 [-3.0339673  0.6642333  1.4921503]]
w2: [[-1.4235711 ]
 [ 2.232318  ]
 [ 0.86814606]]


w1: [[-1.5406665   2.1845064   1.1129699 ]
 [-3.034208    0.66445845  1.4925562 ]]
w2: [[-1.4238185 ]
 [ 2.2326398 ]
 [ 0.86852276]]


w1: [[-1.5409504   2.1847768   1.1133792 ]
 [-3.0344248   0.66466117  1.4929217 ]]
w2: [[-1.4240413]
 [ 2.2329297]
 [ 0.868862 ]]


w1: [[-1.5412061   2.1850202   1.113748  ]
 [-3.03462     0.66484374  1.4932508 ]]
w2: [[-1.4242419 ]
 [ 2.2331908 ]
 [ 0.86916745]]


w1: [[-1.5414364  2.1852396  1.11408  ]
 [-3.0347958  0.6650081  1.4935472]]
w2: [[-1.4244226]
 [ 2.2334259]
 [ 0.8694425]]


w1: [[-1.5416439  2.185437   1.1143789]
 [-3.034954   0.6651562  1.4938141]]
w2: [[

w1: [[-1.5758574  2.2180297  1.1633612]
 [-3.0575464  0.6862812  1.5318224]]
w2: [[-1.4491117 ]
 [ 2.2675076 ]
 [ 0.90750617]]


w1: [[-1.5761303  2.2182899  1.1637491]
 [-3.0576875  0.6864132  1.5320594]]
w2: [[-1.4492819 ]
 [ 2.267766  ]
 [ 0.90777457]]


w1: [[-1.576376    2.218524    1.1640985 ]
 [-3.0578146   0.68653214  1.5322728 ]]
w2: [[-1.4494352 ]
 [ 2.2679987 ]
 [ 0.90801626]]


w1: [[-1.5765972  2.218735   1.1644131]
 [-3.057929   0.6866392  1.532465 ]]
w2: [[-1.4495733]
 [ 2.2682083]
 [ 0.9082339]]


w1: [[-1.5767964  2.218925   1.1646963]
 [-3.058032   0.6867356  1.5326381]]
w2: [[-1.4496976 ]
 [ 2.268397  ]
 [ 0.90842986]]


w1: [[-1.5771209  2.2192342  1.1651576]
 [-3.058285   0.6869722  1.5330623]]
w2: [[-1.4499559]
 [ 2.2687294]
 [ 0.9088214]]


w1: [[-1.5774131  2.2195127  1.1655729]
 [-3.058513   0.6871853  1.5334444]]
w2: [[-1.4501886]
 [ 2.2690287]
 [ 0.909174 ]]


w1: [[-1.5776762   2.2197635   1.1659468 ]
 [-3.0587182   0.68737715  1.5337884 ]]
w2: [[-1.4503981 

w1: [[-1.5951831  2.2364388  1.1908795]
 [-3.077243   0.7046895  1.5646697]]
w2: [[-1.4675198]
 [ 2.288651 ]
 [ 0.9347218]]


w1: [[-1.5953382   2.2365863   1.1911006 ]
 [-3.0774138   0.70484895  1.5649521 ]]
w2: [[-1.4676756 ]
 [ 2.2888243 ]
 [ 0.93495023]]


w1: [[-1.5954779   2.2367194   1.1912997 ]
 [-3.0775676   0.70499253  1.5652064 ]]
w2: [[-1.4678159]
 [ 2.2889802]
 [ 0.9351559]]


w1: [[-1.5956037  2.236839   1.191479 ]
 [-3.077706   0.7051218  1.5654354]]
w2: [[-1.4679422]
 [ 2.2891207]
 [ 0.9353411]]


w1: [[-1.595717   2.2369468  1.1916404]
 [-3.0778308  0.7052382  1.5656416]]
w2: [[-1.4680561]
 [ 2.2892473]
 [ 0.9355079]]


w1: [[-1.595819    2.2370439   1.1917857 ]
 [-3.077943    0.70534307  1.5658274 ]]
w2: [[-1.4681586]
 [ 2.2893612]
 [ 0.9356581]]


w1: [[-1.5959109  2.2371314  1.1919166]
 [-3.0780442  0.7054375  1.5659946]]
w2: [[-1.4682509 ]
 [ 2.2894638 ]
 [ 0.93579334]]


w1: [[-1.5959936  2.23721    1.1920345]
 [-3.0781353  0.7055225  1.5661452]]
w2: [[-1.468334 ]



w1: [[-1.6124673  2.2528677  1.2155038]
 [-3.0962336  0.722418   1.5958445]]
w2: [[-1.4848458 ]
 [ 2.307925  ]
 [ 0.96005875]]


w1: [[-1.6125141  2.2529123  1.2155706]
 [-3.096285   0.722466   1.5959283]]
w2: [[-1.4848926]
 [ 2.3079772]
 [ 0.9601272]]


w1: [[-1.6125563  2.2529523  1.2156307]
 [-3.0963314  0.7225092  1.5960038]]
w2: [[-1.4849348]
 [ 2.3080242]
 [ 0.9601888]]


w1: [[-1.6127609  2.2531466  1.215922 ]
 [-3.0965557  0.7227186  1.5963688]]
w2: [[-1.4851394]
 [ 2.3082519]
 [ 0.9604871]]


w1: [[-1.6129451  2.2533216  1.2161843]
 [-3.0967577  0.7229071  1.5966974]]
w2: [[-1.4853235 ]
 [ 2.308457  ]
 [ 0.96075577]]


w1: [[-1.613111   2.2534792  1.2164204]
 [-3.0969396  0.7230769  1.5969934]]
w2: [[-1.4854895]
 [ 2.3086417]
 [ 0.9609977]]


w1: [[-1.6132604   2.253621    1.2166331 ]
 [-3.0971034   0.72322977  1.59726   ]]
w2: [[-1.4856389 ]
 [ 2.308808  ]
 [ 0.96121556]]


w1: [[-1.6133949   2.253749    1.2168247 ]
 [-3.097251    0.72336745  1.5975    ]]
w2: [[-1.4857733]



w1: [[-1.630128   2.2696247  1.240629 ]
 [-3.1155756  0.7404591  1.6270759]]
w2: [[-1.5024738 ]
 [ 2.3275604 ]
 [ 0.98569906]]


w1: [[-1.6303037  2.2697914  1.2408786]
 [-3.1157677  0.7406382  1.6273834]]
w2: [[-1.5026488]
 [ 2.3277555]
 [ 0.9859528]]


w1: [[-1.6304619  2.2699413  1.2411034]
 [-3.1159408  0.7407995  1.6276602]]
w2: [[-1.5028064 ]
 [ 2.3279312 ]
 [ 0.98618126]]


w1: [[-1.6306044   2.2700765   1.2413058 ]
 [-3.1160965   0.74094474  1.6279094 ]]
w2: [[-1.5029483]
 [ 2.3280892]
 [ 0.986387 ]]


w1: [[-1.6307327  2.270198   1.2414881]
 [-3.1162367  0.7410755  1.6281339]]
w2: [[-1.5030761 ]
 [ 2.3282316 ]
 [ 0.98657227]]


w1: [[-1.6308482  2.2703075  1.2416523]
 [-3.116363   0.7411933  1.6283361]]
w2: [[-1.5031911]
 [ 2.3283598]
 [ 0.9867391]]


w1: [[-1.6309522   2.2704062   1.2418001 ]
 [-3.1164768   0.74129933  1.6285181 ]]
w2: [[-1.5032947]
 [ 2.3284752]
 [ 0.9868893]]


w1: [[-1.6310459  2.270495   1.2419331]
 [-3.1165793  0.7413948  1.628682 ]]
w2: [[-1.503388  ]




w1: [[-1.6497344  2.2882001  1.2684369]
 [-3.1369765  0.7604056  1.6610163]]
w2: [[-1.5219612]
 [ 2.349287 ]
 [ 1.0138552]]


w1: [[-1.6499643  2.2884178  1.2687624]
 [-3.137227   0.7606391  1.6614096]]
w2: [[-1.5221893]
 [ 2.3495414]
 [ 1.0141834]]


w1: [[-1.6501714  2.2886138  1.2690555]
 [-3.1374526  0.7608493  1.6617637]]
w2: [[-1.5223947]
 [ 2.3497705]
 [ 1.0144789]]


w1: [[-1.650358   2.2887902  1.2693194]
 [-3.1376557  0.7610386  1.6620826]]
w2: [[-1.5225796]
 [ 2.3499768]
 [ 1.014745 ]]


w1: [[-1.6505259  2.2889493  1.269557 ]
 [-3.1378386  0.7612091  1.6623697]]
w2: [[-1.5227461]
 [ 2.3501625]
 [ 1.0149846]]


w1: [[-1.6506772   2.2890923   1.269771  ]
 [-3.1380033   0.76136255  1.6626283 ]]
w2: [[-1.522896 ]
 [ 2.3503299]
 [ 1.0152004]]


w1: [[-1.6508133  2.2892213  1.2699636]
 [-3.1381516  0.7615008  1.6628611]]
w2: [[-1.5230311]
 [ 2.3504806]
 [ 1.0153947]]


w1: [[-1.650936    2.2893374   1.2701372 ]
 [-3.1382852   0.76162523  1.6630708 ]]
w2: [[-1.5231527]
 [ 2.3506



w1: [[-1.6701059   2.307469    1.2971921 ]
 [-3.159128    0.78104365  1.6954746 ]]
w2: [[-1.5421227]
 [ 2.3717818]
 [ 1.0427506]]


w1: [[-1.670235   2.307591   1.2973738]
 [-3.1592681  0.7811741  1.6956904]]
w2: [[-1.5422502]
 [ 2.3719242]
 [ 1.0429325]]


w1: [[-1.6703513  2.3077009  1.2975373]
 [-3.1593943  0.7812916  1.6958847]]
w2: [[-1.542365 ]
 [ 2.3720522]
 [ 1.0430963]]


w1: [[-1.6704559  2.3077998  1.2976847]
 [-3.1595078  0.7813974  1.6960597]]
w2: [[-1.5424683]
 [ 2.3721676]
 [ 1.0432438]]


w1: [[-1.6705501   2.307889    1.2978173 ]
 [-3.15961     0.78149265  1.6962173 ]]
w2: [[-1.5425614]
 [ 2.3722715]
 [ 1.0433766]]


w1: [[-1.670635   2.307969   1.2979368]
 [-3.159702   0.7815784  1.6963592]]
w2: [[-1.5426452]
 [ 2.372365 ]
 [ 1.0434961]]


w1: [[-1.6707114   2.3080413   1.2980443 ]
 [-3.159785    0.78165567  1.696487  ]]
w2: [[-1.5427207]
 [ 2.3724492]
 [ 1.0436038]]


w1: [[-1.6707802  2.3081064  1.2981411]
 [-3.1598597  0.7817252  1.696602 ]]
w2: [[-1.5427886]
 [ 

w1: [[-1.6919562  2.3281085  1.3278356]
 [-3.1827955  0.8030872  1.7315476]]
w2: [[-1.5636581]
 [ 2.3958187]
 [ 1.0733272]]


w1: [[-1.6921425  2.3282845  1.3280959]
 [-3.182997   0.8032748  1.7318513]]
w2: [[-1.5638413]
 [ 2.3960233]
 [ 1.0735861]]


w1: [[-1.6923103   2.3284428   1.3283303 ]
 [-3.1831784   0.80344373  1.7321248 ]]
w2: [[-1.5640063]
 [ 2.3962076]
 [ 1.0738192]]


w1: [[-1.6924615   2.3285854   1.3285414 ]
 [-3.1833417   0.80359584  1.7323711 ]]
w2: [[-1.564155 ]
 [ 2.3963735]
 [ 1.0740291]]


w1: [[-1.6925975  2.328714   1.3287314]
 [-3.1834888  0.8037328  1.7325928]]
w2: [[-1.5642889]
 [ 2.396523 ]
 [ 1.0742182]]


w1: [[-1.69272     2.3288295   1.3289026 ]
 [-3.1836214   0.80385613  1.7327925 ]]
w2: [[-1.5644094]
 [ 2.3966575]
 [ 1.0743884]]


w1: [[-1.6928304  2.3289337  1.3290567]
 [-3.1837406  0.8039672  1.7329723]]
w2: [[-1.5645179]
 [ 2.3967786]
 [ 1.0745417]]


w1: [[-1.6929297  2.3290274  1.3291955]
 [-3.183848   0.8040672  1.7331342]]
w2: [[-1.5646156]
 [ 2.



w1: [[-1.7139455  2.3488548  1.3584261]
 [-3.2065191  0.8251814  1.7669599]]
w2: [[-1.5852443]
 [ 2.4199114]
 [ 1.103661 ]]


w1: [[-1.7140737  2.3489757  1.3586036]
 [-3.2066572  0.82531    1.7671639]]
w2: [[-1.58537  ]
 [ 2.4200516]
 [ 1.1038365]]


w1: [[-1.714189    2.3490846   1.3587635 ]
 [-3.2067814   0.82542574  1.7673476 ]]
w2: [[-1.5854831]
 [ 2.4201777]
 [ 1.1039946]]


w1: [[-1.714293   2.3491826  1.3589075]
 [-3.2068932  0.82553    1.7675129]]
w2: [[-1.5855849]
 [ 2.4202914]
 [ 1.104137 ]]


w1: [[-1.7143866   2.3492708   1.359037  ]
 [-3.206994    0.82562387  1.7676618 ]]
w2: [[-1.5856766]
 [ 2.4203937]
 [ 1.1042651]]


w1: [[-1.7144709  2.3493502  1.3591537]
 [-3.207085   0.8257084  1.7677959]]
w2: [[-1.5857592]
 [ 2.420486 ]
 [ 1.1043805]]


w1: [[-1.7145468  2.3494217  1.3592589]
 [-3.2071667  0.8257845  1.7679167]]
w2: [[-1.5858335]
 [ 2.420569 ]
 [ 1.1044844]]


w1: [[-1.7146151   2.349486    1.3593535 ]
 [-3.2072403   0.82585305  1.7680254 ]]
w2: [[-1.5859005]
 [ 



w1: [[-1.7368745  2.3704672  1.3900281]
 [-3.2311575  0.8481315  1.8029797]]
w2: [[-1.6076698]
 [ 2.444933 ]
 [ 1.134824 ]]


w1: [[-1.7369457  2.3705344  1.3901259]
 [-3.231234   0.8482027  1.8030905]]
w2: [[-1.6077394]
 [ 2.4450107]
 [ 1.1349202]]


w1: [[-1.7370099   2.370595    1.390214  ]
 [-3.231303    0.84826684  1.8031901 ]]
w2: [[-1.6078022]
 [ 2.4450805]
 [ 1.1350069]]


w1: [[-1.7370677  2.3706493  1.3902932]
 [-3.231365   0.8483246  1.8032799]]
w2: [[-1.6078585]
 [ 2.4451435]
 [ 1.1350849]]


w1: [[-1.7373475  2.3709128  1.3906766]
 [-3.231665   0.848604   1.8037132]]
w2: [[-1.6081315]
 [ 2.445448 ]
 [ 1.1354618]]


w1: [[-1.7375994  2.37115    1.3910218]
 [-3.231935   0.8488556  1.8041035]]
w2: [[-1.6083773]
 [ 2.445722 ]
 [ 1.1358012]]


w1: [[-1.7378262  2.3713636  1.3913326]
 [-3.2321782  0.8490822  1.8044549]]
w2: [[-1.6085987]
 [ 2.445969 ]
 [ 1.1361068]]


w1: [[-1.7380304   2.371556    1.3916125 ]
 [-3.232397    0.84928614  1.8047713 ]]
w2: [[-1.608798 ]
 [ 2.4461

w1: [[-1.762428   2.3945377  1.424862 ]
 [-3.2584987  0.8736102  1.8420944]]
w2: [[-1.6325723]
 [ 2.4726982]
 [ 1.1690025]]


w1: [[-1.7625108  2.3946157  1.4249741]
 [-3.258587   0.8736925  1.8422195]]
w2: [[-1.6326528]
 [ 2.4727879]
 [ 1.1691123]]


w1: [[-1.7625853  2.3946857  1.425075 ]
 [-3.2586663  0.8737666  1.842332 ]]
w2: [[-1.6327252]
 [ 2.4728687]
 [ 1.1692111]]


w1: [[-1.7626523   2.394749    1.4251659 ]
 [-3.2587378   0.87383336  1.8424333 ]]
w2: [[-1.6327904]
 [ 2.4729414]
 [ 1.1693001]]


w1: [[-1.7627126   2.3948057   1.4252477 ]
 [-3.2588022   0.87389344  1.8425246 ]]
w2: [[-1.6328492]
 [ 2.473007 ]
 [ 1.1693802]]


w1: [[-1.7630047  2.3950808  1.4256432]
 [-3.259114   0.8741841  1.8429651]]
w2: [[-1.6331333]
 [ 2.4733236]
 [ 1.1697673]]


w1: [[-1.7632676   2.3953285   1.4259993 ]
 [-3.2593946   0.87444574  1.8433617 ]]
w2: [[-1.6333891]
 [ 2.4736087]
 [ 1.1701158]]


w1: [[-1.7635045   2.3955514   1.42632   ]
 [-3.2596474   0.87468135  1.8437189 ]]
w2: [[-1.6336194]

w2: [[-1.657427 ]
 [ 2.5003817]
 [ 1.2026651]]


w1: [[-1.7882181   2.4188194   1.459587  ]
 [-3.2859712   0.89922893  1.8805462 ]]
w2: [[-1.6576201]
 [ 2.5005968]
 [ 1.202925 ]]


w1: [[-1.7883976  2.4189882  1.459827 ]
 [-3.286162   0.8994068  1.8808103]]
w2: [[-1.657794 ]
 [ 2.5007904]
 [ 1.203159 ]]


w1: [[-1.7885591   2.4191403   1.4600431 ]
 [-3.2863336   0.89956695  1.881048  ]]
w2: [[-1.6579506]
 [ 2.5009646]
 [ 1.2033696]]


w1: [[-1.7887045   2.4192772   1.4602376 ]
 [-3.286488    0.89971113  1.8812621 ]]
w2: [[-1.6580917]
 [ 2.5011215]
 [ 1.2035593]]


w1: [[-1.7888354  2.4194005  1.4604129]
 [-3.2866273  0.899841   1.8814548]]
w2: [[-1.6582186]
 [ 2.501263 ]
 [ 1.2037301]]


w1: [[-1.7889533   2.4195116   1.4605706 ]
 [-3.2867527   0.89995795  1.8816284 ]]
w2: [[-1.658333 ]
 [ 2.5013902]
 [ 1.2038839]]


w1: [[-1.7890595  2.4196115  1.4607127]
 [-3.2868655  0.9000632  1.8817847]]
w2: [[-1.658436 ]
 [ 2.501505 ]
 [ 1.2040224]]


w1: [[-1.7891551   2.4197013   1.4608406 ]
 [



w1: [[-1.814611   2.4436615  1.4946637]
 [-3.313966   0.9253567  1.9189085]]
w2: [[-1.683176 ]
 [ 2.5290198]
 [ 1.2370665]]


w1: [[-1.814676   2.4437227  1.4947497]
 [-3.314035   0.925421   1.9190019]]
w2: [[-1.683239 ]
 [ 2.5290897]
 [ 1.23715  ]]


w1: [[-1.8149905  2.4440188  1.4951645]
 [-3.3143678  0.9257318  1.9194528]]
w2: [[-1.683543 ]
 [ 2.5294275]
 [ 1.2375531]]


w1: [[-1.8152738  2.4442854  1.4955381]
 [-3.3146675  0.9260116  1.9198588]]
w2: [[-1.6838168]
 [ 2.5297318]
 [ 1.2379161]]


w1: [[-1.8155288   2.4445255   1.4958745 ]
 [-3.3149374   0.92626363  1.9202244 ]]
w2: [[-1.6840633]
 [ 2.5300057]
 [ 1.238243 ]]


w1: [[-1.8157583   2.4447415   1.4961774 ]
 [-3.3151803   0.92649055  1.9205537 ]]
w2: [[-1.6842853]
 [ 2.5302525]
 [ 1.2385373]]


w1: [[-1.815965    2.444936    1.4964502 ]
 [-3.3153992   0.92669487  1.9208502 ]]
w2: [[-1.6844852]
 [ 2.5304747]
 [ 1.2388023]]


w1: [[-1.8161513   2.4451113   1.4966958 ]
 [-3.315596    0.92687887  1.9211171 ]]
w2: [[-1.684665



w1: [[-1.8442729   2.4715827   1.5335275 ]
 [-3.345292    0.95462376  1.960922  ]]
w2: [[-1.7118158]
 [ 2.5608184]
 [ 1.2747778]]


w1: [[-1.8445106  2.4718063  1.5338365]
 [-3.3455424  0.9548578  1.9612541]]
w2: [[-1.712045 ]
 [ 2.5610726]
 [ 1.2750771]]


w1: [[-1.8447245   2.4720078   1.5341147 ]
 [-3.345768    0.95506865  1.9615532 ]]
w2: [[-1.7122513]
 [ 2.5613015]
 [ 1.2753466]]


w1: [[-1.8449172  2.4721892  1.5343652]
 [-3.345971   0.9552584  1.9618225]]
w2: [[-1.7124372]
 [ 2.5615075]
 [ 1.2755893]]


w1: [[-1.8450907  2.4723525  1.5345907]
 [-3.346154   0.9554293  1.962065 ]]
w2: [[-1.7126044]
 [ 2.561693 ]
 [ 1.275808 ]]


w1: [[-1.845247   2.4724996  1.5347939]
 [-3.3463185  0.9555832  1.9622834]]
w2: [[-1.7127551]
 [ 2.56186  ]
 [ 1.2760048]]


w1: [[-1.8453877  2.472632   1.5349767]
 [-3.3464668  0.9557218  1.96248  ]]
w2: [[-1.7128907]
 [ 2.5620105]
 [ 1.276182 ]]


w1: [[-1.8455144  2.4727511  1.5351415]
 [-3.3466003  0.9558466  1.962657 ]]
w2: [[-1.7130129]
 [ 2.5621



w1: [[-1.8730714   2.4986966   1.5707054 ]
 [-3.3755744   0.98295164  2.000697  ]]
w2: [[-1.7395515]
 [ 2.5915492]
 [ 1.3107641]]


w1: [[-1.8734074  2.499013   1.5711356]
 [-3.3759267  0.9832816  2.001155 ]]
w2: [[-1.7398747]
 [ 2.5919068]
 [ 1.3111801]]


w1: [[-1.8737099   2.4992979   1.5715231 ]
 [-3.376244    0.98357874  2.0015674 ]]
w2: [[-1.7401657]
 [ 2.592229 ]
 [ 1.3115547]]


w1: [[-1.8739823  2.4995544  1.571872 ]
 [-3.37653    0.9838463  2.0019388]]
w2: [[-1.7404277]
 [ 2.5925188]
 [ 1.311892 ]]


w1: [[-1.8742276  2.4997854  1.5721861]
 [-3.3767872  0.9840872  2.0022733]]
w2: [[-1.7406636]
 [ 2.5927799]
 [ 1.3121958]]


w1: [[-1.8744485   2.4999933   1.572469  ]
 [-3.377019    0.98430413  2.0025744 ]]
w2: [[-1.7408761]
 [ 2.593015 ]
 [ 1.3124692]]


w1: [[-1.8746474   2.5001807   1.5727237 ]
 [-3.3772275   0.98449945  2.0028455 ]]
w2: [[-1.7410674]
 [ 2.5932267]
 [ 1.3127155]]


w1: [[-1.8748264   2.5003493   1.5729531 ]
 [-3.3774154   0.98467535  2.0030897 ]]
w2: [[-1.



w1: [[-1.9032216  2.5270956  1.6090584]
 [-3.4071467  1.0125282  2.0413616]]
w2: [[-1.7685275]
 [ 2.6235807]
 [ 1.3478174]]


w1: [[-1.9033304  2.527198   1.6091958]
 [-3.4072604  1.0126349  2.0415068]]
w2: [[-1.768632 ]
 [ 2.623696 ]
 [ 1.3479502]]


w1: [[-1.9034284  2.5272903  1.6093197]
 [-3.407363   1.012731   2.0416374]]
w2: [[-1.7687261]
 [ 2.6238   ]
 [ 1.3480698]]


w1: [[-1.9035167  2.5273736  1.6094311]
 [-3.4074552  1.0128174  2.0417552]]
w2: [[-1.7688109]
 [ 2.6238935]
 [ 1.3481774]]


w1: [[-1.9035962  2.5274484  1.6095315]
 [-3.4075382  1.0128952  2.0418613]]
w2: [[-1.7688872]
 [ 2.6239777]
 [ 1.3482744]]


w1: [[-1.9036677  2.527516   1.6096219]
 [-3.407613   1.0129653  2.0419567]]
w2: [[-1.7689558]
 [ 2.6240535]
 [ 1.3483616]]


w1: [[-1.9040135  2.5278418  1.6100582]
 [-3.4079742  1.0133041  2.042417 ]]
w2: [[-1.7692878]
 [ 2.62442  ]
 [ 1.3487828]]


w1: [[-1.9043249  2.5281353  1.610451 ]
 [-3.4082997  1.0136092  2.0428317]]
w2: [[-1.7695868]
 [ 2.62475  ]
 [ 1.34

w1: [[-1.9319855  2.5542061  1.6451284]
 [-3.4371529  1.0406784  2.0793123]]
w2: [[-1.7961246]
 [ 2.6540143]
 [ 1.3826175]]


w1: [[-1.932076   2.5542915  1.645241 ]
 [-3.437247   1.0407668  2.0794306]]
w2: [[-1.7962112]
 [ 2.65411  ]
 [ 1.3827262]]


w1: [[-1.9321574  2.5543683  1.6453425]
 [-3.437332   1.0408465  2.079537 ]]
w2: [[-1.7962893]
 [ 2.654196 ]
 [ 1.3828241]]


w1: [[-1.9322307  2.5544374  1.6454338]
 [-3.4374082  1.0409181  2.0796328]]
w2: [[-1.7963597]
 [ 2.6542735]
 [ 1.3829122]]


w1: [[-1.932585   2.5547714  1.6458746]
 [-3.437777   1.0412644  2.0800948]]
w2: [[-1.7966993]
 [ 2.6546476]
 [ 1.3833373]]


w1: [[-1.932904   2.5550723  1.6462716]
 [-3.4381092  1.0415763  2.0805109]]
w2: [[-1.797005 ]
 [ 2.6549845]
 [ 1.38372  ]]


w1: [[-1.9331913  2.5553432  1.646629 ]
 [-3.4384081  1.041857   2.0808854]]
w2: [[-1.7972804]
 [ 2.6552877]
 [ 1.3840647]]


w1: [[-1.93345    2.555587   1.6469508]
 [-3.4386773  1.0421098  2.0812228]]
w2: [[-1.7975284]
 [ 2.6555607]
 [ 1.3843

In [26]:
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)))
learning_rate = 0.001
train_step = tf.train.AdamOptimizer(learing_rete).minimize(cross_entropy)

NameError: name 'learing_rete' is not defined

In [ ]:
import tensorflow as tf

# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)
    A = tf.constant(1234)
    print(sess.run(A))
    print(sess.run(tf.constant([123,456,789])))

In [ ]:
x1 = tf.add(5,2)
print(x1.shape)

In [ ]:
a = tf.constant([1.0, 2.0])
b = tf.constant([2.0, 3.0])
result = a + b
print(a.graph is tf.get_default_graph())

In [ ]:
print(a.graph)

In [ ]:
gl = tf.Graph()
with gl.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.zeros_initializer)
    print(v)

In [ ]:
tf.GraphKeys.VARIABLES

In [ ]:
tf.GraphKeys.GLOBAL_VARIABLES 

In [ ]:
tf.GraphKeys.QUEUE_RUNNERS

In [ ]:
tf.Variable

In [ ]:
# declare 2 * 3 matrix
weights = tf.Variable(tf.random_normal([2,3],stddev=2))
weights

In [ ]:
biases = tf.Variable(tf.zeros([3]))

In [ ]:
w2 = tf.Variable(weights.initialized_value())
w2

In [ ]:
w3 = tf.Variable(weights.initialized_value() * 2.0)
w3

In [ ]:
sess = tf.Session()
w4 = tf.Variable(tf.random_normal([2,3],stddev=2, seed=1))
w5 = tf.Variable(tf.random_normal([3,1],stddev=1, seed=1))
x2 = tf.constant([[0.7,0.9]])
a = tf.matmul(x2, w4)
y = tf.matmul(a, w5)
sess.run(w4.initializer)
sess.run(w5.initializer)
print(w4)
print(w5)
print(sess.run(y))

In [ ]:
init_op = tf.initialize_all_variables() # 自动处理变量间的依赖关系
print(sess.run(init_op))

In [ ]:
tf.GraphKeys.TRAINABLE_VARIABLES # TRAINABLE_VARIABLES中的变量作为默认优化对象

In [ ]:
tf.trainable_variables #所有需要优化的参数

In [27]:
sess = tf.Session()
w5 = tf.Variable(tf.random_normal([2,3],stddev=1))
w6 = tf.Variable(tf.random_normal([3,1],stddev=1))
x3 = tf.placeholder(tf.float32, shape=(1,2), name='input')
x4 = tf.matmul(x3, w5)
y = tf.matmul(x4, w6)
init_op = tf.initialize_all_variables()
sess.run(init_op)
print(sess.run(y, feed_dict={x3:[[0.7,0.9]]}))

[[-4.1698127]]


In [28]:
sess = tf.Session()
w5 = tf.Variable(tf.random_normal([2,3],stddev=1))
w6 = tf.Variable(tf.random_normal([3,1],stddev=1))
x3 = tf.placeholder(tf.float32, shape=(3,2), name='input')
x4 = tf.matmul(x3, w5)
y = tf.matmul(x4, w6)
init_op = tf.initialize_all_variables()
sess.run(init_op)
print(sess.run(y, feed_dict={x3:[[0.7,0.9],[0.1,0.4],[0.5,0.8]]}))

[[-2.13708  ]
 [-0.2192412]
 [-1.4766638]]


In [33]:
tf.log(10)

TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64, complex64, complex128

In [29]:
print(tf.reduce_sum([1,2]))

Tensor("Sum_1:0", shape=(), dtype=int32)


In [30]:
print(tf.log(16))

TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64, complex64, complex128

In [31]:
tf.log(100)

TypeError: Value passed to parameter 'x' has DataType int32 not in list of allowed values: float16, bfloat16, float32, float64, complex64, complex128

Weights:
[[-1.3336271  -0.09045336 -0.17338656]
 [-0.5119246  -0.22988157 -0.56073236]]
Bias:
[-0.78012824  1.0783366   0.52476186]
