In [1]:
import tensorflow as tf

# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)
    A = tf.constant(1234)
    print(sess.run(A))
    print(sess.run(tf.constant([123,456,789])))

b'Hello World!'
1234
[123 456 789]


In [2]:
x1 = tf.add(5,2)
print(x1.shape)

()


In [3]:
a = tf.constant([1.0, 2.0])
b = tf.constant([2.0, 3.0])
result = a + b
print(a.graph is tf.get_default_graph())

True


In [4]:
print(a.graph)

In [5]:
gl = tf.Graph()
with gl.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.zeros_initializer)
    print(v)

<tf.Variable 'v:0' shape=(1,) dtype=float32_ref>


In [6]:
tf.GraphKeys.VARIABLES

'variables'

In [7]:
tf.GraphKeys.GLOBAL_VARIABLES 

'variables'

In [8]:
tf.GraphKeys.QUEUE_RUNNERS

'queue_runners'

In [9]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [10]:
# declare 2 * 3 matrix
weights = tf.Variable(tf.random_normal([2,3],stddev=2))
weights

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>

In [11]:
biases = tf.Variable(tf.zeros([3]))

In [12]:
w2 = tf.Variable(weights.initialized_value())
w2

<tf.Variable 'Variable_2:0' shape=(2, 3) dtype=float32_ref>

In [13]:
w3 = tf.Variable(weights.initialized_value() * 2.0)
w3

<tf.Variable 'Variable_3:0' shape=(2, 3) dtype=float32_ref>

In [25]:
sess = tf.Session()
w4 = tf.Variable(tf.random_normal([2,3],stddev=2, seed=1))
w5 = tf.Variable(tf.random_normal([3,1],stddev=1, seed=1))
x2 = tf.constant([[0.7,0.9]])
a = tf.matmul(x2, w4)
y = tf.matmul(a, w5)
sess.run(w4.initializer)
sess.run(w5.initializer)
print(w4)
print(w5)
print(sess.run(y))

<tf.Variable 'Variable_20:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_21:0' shape=(3, 1) dtype=float32_ref>
[[ 7.91515589]]


In [16]:
init_op = tf.initialize_all_variables() # 自动处理变量间的依赖关系
print(sess.run(init_op))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
None


In [17]:
tf.GraphKeys.TRAINABLE_VARIABLES # TRAINABLE_VARIABLES中的变量作为默认优化对象

'trainable_variables'

In [18]:
tf.trainable_variables #所有需要优化的参数

<function tensorflow.python.ops.variables.trainable_variables>

In [23]:
sess = tf.Session()
w5 = tf.Variable(tf.random_normal([2,3],stddev=1))
w6 = tf.Variable(tf.random_normal([3,1],stddev=1))
x3 = tf.placeholder(tf.float32, shape=(1,2), name='input')
x4 = tf.matmul(x3, w5)
y = tf.matmul(x4, w6)
init_op = tf.initialize_all_variables()
sess.run(init_op)
print(sess.run(y, feed_dict={x3:[[0.7,0.9]]}))

[[-0.48008552]]


In [26]:
sess = tf.Session()
w5 = tf.Variable(tf.random_normal([2,3],stddev=1))
w6 = tf.Variable(tf.random_normal([3,1],stddev=1))
x3 = tf.placeholder(tf.float32, shape=(3,2), name='input')
x4 = tf.matmul(x3, w5)
y = tf.matmul(x4, w6)
init_op = tf.initialize_all_variables()
sess.run(init_op)
print(sess.run(y, feed_dict={x3:[[0.7,0.9],[0.1,0.4],[0.5,0.8]]}))

[[-1.21743679]
 [-0.16191274]
 [-0.86264646]]


In [27]:
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)))
learning_rate = 0.001
train_step = tf.train.AdamOptimizer(learing_rete).minimize(cross_entropy)

NameError: name 'y_' is not defined

In [29]:
import tensorflow as tf
from numpy.random import RandomState
#### 1. 定义神经网络的参数，输入和输出节点。
batch_size = 8
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))


x = tf.placeholder(tf.float32, shape=(None, 2), name='x-input')
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')



#### 2. 定义前向传播过程，损失函数及反向传播算法。"
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

####  3. 生成模拟数据集。
rdm = RandomState(1)
X = rdm.rand(128,2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

#### 4. 创建一个会话来运行TensorFlow程序。
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print ("w1:", sess.run(w1))
    print ("w2:", sess.run(w2))
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))

        # 输出训练后的参数取值。
        print("\n")
        print("w1:", sess.run(w1))
        print("w2:", sess.run(w2))

w1: [[-0.81131822  1.48459876  0.06532937]
 [-2.4427042   0.0992484   0.59122431]]
w2: [[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
After 0 training step(s), cross entropy on all data is 0.0674925


w1: [[-0.81231821  1.4855988   0.06632921]
 [-2.44370413  0.1002484   0.59222424]]
w2: [[-0.81231821]
 [ 1.4855988 ]
 [ 0.06632937]]


w1: [[-0.8132937   1.48657429  0.06730329]
 [-2.44465828  0.1012025   0.59318024]]
w2: [[-0.81329739]
 [ 1.48658359]
 [ 0.06729427]]


w1: [[-0.81404775  1.48732841  0.06805624]
 [-2.44539595  0.10194003  0.59391922]]
w2: [[-0.81405431]
 [ 1.48734486]
 [ 0.06804014]]


w1: [[-0.81466544  1.48794615  0.06867302]
 [-2.4460001   0.10254417  0.59452456]]
w2: [[-0.81467432]
 [ 1.48796844]
 [ 0.06865111]]


w1: [[-0.81518751  1.48846829  0.06919434]
 [-2.44651079  0.1030548   0.59503621]]
w2: [[-0.81519836]
 [ 1.48849547]
 [ 0.06916752]]


w1: [[-0.81563747  1.4889183   0.06964365]
 [-2.44695091  0.1034949   0.59547716]]
w2: [[-0.81565005]
 [ 1.48894978]
 [ 0.069

w2: [[-0.86895341]
 [ 1.54558432]
 [ 0.12258578]]


w1: [[-0.871903    1.54488826  0.13170621]
 [-2.49817538  0.15443935  0.65221673]]
w2: [[-0.86948663]
 [ 1.54618895]
 [ 0.12312778]]


w1: [[-0.87254745  1.54552543  0.13248368]
 [-2.4988203   0.15507665  0.65300119]]
w2: [[-0.87014866]
 [ 1.54685569]
 [ 0.12381158]]


w1: [[-0.8731966   1.54616702  0.13326959]
 [-2.49949193  0.15574016  0.65382063]]
w2: [[-0.8708334 ]
 [ 1.54753017]
 [ 0.12452136]]


w1: [[-0.87384331  1.5468061   0.13405524]
 [-2.50019312  0.15643273  0.65467852]]
w2: [[-0.87154192]
 [ 1.54820657]
 [ 0.12525897]]


w1: [[-0.87457889  1.5475328   0.13495046]
 [-2.50084043  0.15707205  0.65547109]]
w2: [[-0.87222403]
 [ 1.54895604]
 [ 0.12595879]]


w1: [[-0.87524468  1.54819047  0.13576077]
 [-2.50142646  0.15765074  0.65618849]]
w2: [[-0.87284148]
 [ 1.54963446]
 [ 0.12659223]]


w1: [[-0.87585956  1.54879785  0.13650978]
 [-2.50208855  0.15830442  0.65700221]]
w2: [[-0.87351257]
 [ 1.55027819]
 [ 0.12729143]]


w1:

 [ 0.17093176]]


w1: [[-0.91672707  1.58893859  0.18897413]
 [-2.54301882  0.19850643  0.70947355]]
w2: [[-0.91523272]
 [ 1.59273946]
 [ 0.17164122]]


w1: [[-0.91738492  1.58958101  0.18985912]
 [-2.54364824  0.19912155  0.71031082]]
w2: [[-0.91587603]
 [ 1.59342086]
 [ 0.17234103]]


w1: [[-0.91797894  1.59016109  0.19065827]
 [-2.54421663  0.19967701  0.71106684]]
w2: [[-0.91645694]
 [ 1.59403622]
 [ 0.17297296]]


w1: [[-0.91851538  1.59068489  0.1913799 ]
 [-2.54472995  0.20017858  0.71174955]]
w2: [[-0.91698152]
 [ 1.59459186]
 [ 0.17354359]]


w1: [[-0.91899973  1.59115791  0.19203152]
 [-2.54519343  0.20063148  0.71236598]]
w2: [[-0.9174552 ]
 [ 1.59509361]
 [ 0.17405885]]


w1: [[-0.91943711  1.59158504  0.19261989]
 [-2.54561186  0.20104045  0.71292263]]
w2: [[-0.91788292]
 [ 1.5955466 ]
 [ 0.17452411]]


w1: [[-0.9199425   1.59207833  0.1933032 ]
 [-2.54604793  0.20146641  0.71350533]]
w2: [[-0.918338  ]
 [ 1.59606218]
 [ 0.17501795]]


w1: [[-0.9205088   1.59263086  0.1940

w1: [[-0.9647246   1.63553739  0.25607169]
 [-2.59257007  0.24667341  0.77731961]]
w2: [[-0.96482456]
 [ 1.64336312]
 [ 0.22718133]]


w1: [[-0.96512896  1.63592756  0.25665715]
 [-2.59304452  0.24713223  0.77798355]]
w2: [[-0.96528614]
 [ 1.6438036 ]
 [ 0.22771253]]


w1: [[-0.96549368  1.63627946  0.25718525]
 [-2.59347248  0.24754608  0.77858239]]
w2: [[-0.96570247]
 [ 1.64420092]
 [ 0.22819166]]


w1: [[-0.96595061  1.63672006  0.25784868]
 [-2.59405327  0.24810758  0.77939445]]
w2: [[-0.96625984]
 [ 1.64470792]
 [ 0.22883461]]


w1: [[-0.9665029   1.63725245  0.25865057]
 [-2.59461808  0.24865347  0.78018481]]
w2: [[-0.96682227]
 [ 1.64529264]
 [ 0.22948152]]


w1: [[-0.96700108  1.63773263  0.25937384]
 [-2.59512734  0.24914585  0.78089768]]
w2: [[-0.96732956]
 [ 1.64582002]
 [ 0.230065  ]]


w1: [[-0.96745038  1.63816583  0.26002622]
 [-2.59558678  0.24958996  0.78154063]]
w2: [[-0.96778715]
 [ 1.64629567]
 [ 0.2305913 ]]


w1: [[-0.96785563  1.63855648  0.26061463]
 [-2.5960011

 [ 0.27921131]]


w1: [[-1.00796449  1.67703247  0.31990188]
 [-2.63813734  0.29055345  0.84178728]]
w2: [[-1.00974798]
 [ 1.6896193 ]
 [ 0.27976948]]


w1: [[-1.00848043  1.67752552  0.32067299]
 [-2.63868165  0.29107538  0.84256977]]
w2: [[-1.01028192]
 [ 1.69017482]
 [ 0.28040716]]


w1: [[-1.00894558  1.67797005  0.32136816]
 [-2.63917232  0.29154593  0.84327519]]
w2: [[-1.01076329]
 [ 1.69067562]
 [ 0.28098205]]


w1: [[-1.00936496  1.67837071  0.32199487]
 [-2.63961482  0.29197013  0.84391117]]
w2: [[-1.01119721]
 [ 1.69112706]
 [ 0.28150031]]


w1: [[-1.00974309  1.67873192  0.32255986]
 [-2.64001369  0.29235256  0.84448451]]
w2: [[-1.01158845]
 [ 1.69153404]
 [ 0.28196755]]


w1: [[-1.01021707  1.67918468  0.32326919]
 [-2.64042521  0.29274705  0.84507704]]
w2: [[-1.01200783]
 [ 1.69202375]
 [ 0.28246906]]


w1: [[-1.01079082  1.67973268  0.32412684]
 [-2.64083815  0.29314286  0.84567243]]
w2: [[-1.01244724]
 [ 1.69259667]
 [ 0.28299507]]


w1: [[-1.01130807  1.68022668  0.3249



w1: [[-1.05252171  1.71953571  0.38662207]
 [-2.67588496  0.32665879  0.89694947]]
w2: [[-1.0483402 ]
 [ 1.73557365]
 [ 0.32677561]]


w1: [[-1.05307186  1.72005987  0.38744608]
 [-2.6762383   0.32699579  0.89747769]]
w2: [[-1.04872656]
 [ 1.73611522]
 [ 0.32725909]]


w1: [[-1.05358124  1.72054517  0.38820913]
 [-2.67669916  0.32743528  0.8981663 ]]
w2: [[-1.04918969]
 [ 1.73665011]
 [ 0.32783559]]


w1: [[-1.05404031  1.72098255  0.38889685]
 [-2.67711449  0.32783139  0.8987869 ]]
w2: [[-1.04960704]
 [ 1.73713219]
 [ 0.32835516]]


w1: [[-1.05445397  1.72137678  0.38951665]
 [-2.6774888   0.32818836  0.89934623]]
w2: [[-1.04998314]
 [ 1.73756671]
 [ 0.32882342]]


w1: [[-1.05482686  1.72173202  0.39007527]
 [-2.67782617  0.32851008  0.89985037]]
w2: [[-1.05032218]
 [ 1.73795831]
 [ 0.32924545]]


w1: [[-1.05529892  1.7221818   0.39078298]
 [-2.67818427  0.3288517   0.90038639]]
w2: [[-1.05069709]
 [ 1.73843694]
 [ 0.32971409]]


w1: [[-1.05587423  1.72272992  0.39164424]
 [-2.67855


w1: [[-1.09060061  1.75581884  0.44359609]
 [-2.70474172  0.35414612  0.94080764]]
w2: [[-1.0785327 ]
 [ 1.77426791]
 [ 0.36511883]]


w1: [[-1.09094942  1.75615108  0.44411814]
 [-2.7050786   0.3544665   0.94132715]]
w2: [[-1.07886553]
 [ 1.77464187]
 [ 0.36554587]]


w1: [[-1.09126365  1.75645053  0.44458857]
 [-2.70538211  0.35475519  0.94179529]]
w2: [[-1.07916546]
 [ 1.77497888]
 [ 0.36593068]]


w1: [[-1.09169972  1.75686598  0.44524175]
 [-2.70570135  0.35505879  0.94228822]]
w2: [[-1.07950222]
 [ 1.77542031]
 [ 0.36636692]]


w1: [[-1.09209263  1.7572403   0.44583032]
 [-2.70598888  0.35533234  0.94273239]]
w2: [[-1.07980573]
 [ 1.77581811]
 [ 0.36676002]]


w1: [[-1.09244668  1.75757754  0.44636068]
 [-2.70624804  0.35557884  0.94313264]]
w2: [[-1.0800792 ]
 [ 1.77617657]
 [ 0.36711425]]


w1: [[-1.09276569  1.75788152  0.44683856]
 [-2.70648146  0.35580096  0.94349331]]
w2: [[-1.0803256 ]
 [ 1.77649951]
 [ 0.36743343]]


w1: [[-1.09305322  1.75815535  0.44726917]
 [-2.706691

w1: [[-1.12394726  1.78756964  0.49361196]
 [-2.72883606  0.37703353  0.97845131]]
w2: [[-1.10403728]
 [ 1.8079952 ]
 [ 0.39862242]]


w1: [[-1.12427938  1.7878859   0.49410978]
 [-2.72904253  0.37722951  0.97877955]]
w2: [[-1.10426545]
 [ 1.80832303]
 [ 0.39892867]]


w1: [[-1.12465811  1.78824663  0.49467772]
 [-2.72933555  0.37750757  0.97924548]]
w2: [[-1.10456967]
 [ 1.80871189]
 [ 0.3993336 ]]


w1: [[-1.12507021  1.78863907  0.49529588]
 [-2.72971296  0.37786567  0.97984505]]
w2: [[-1.10494554]
 [ 1.80915022]
 [ 0.39983067]]


w1: [[-1.12563944  1.78918135  0.49614677]
 [-2.73006868  0.37820327  0.98041034]]
w2: [[-1.1053381 ]
 [ 1.80971265]
 [ 0.40035835]]


w1: [[-1.12615228  1.78966987  0.4969134 ]
 [-2.73038912  0.37850744  0.98091966]]
w2: [[-1.10569179]
 [ 1.81021941]
 [ 0.40083379]]


w1: [[-1.12661433  1.79011011  0.4976041 ]
 [-2.73067784  0.37878147  0.98137856]]
w2: [[-1.10601044]
 [ 1.81067598]
 [ 0.40126213]]


w1: [[-1.12703061  1.79050672  0.4982264 ]
 [-2.7309379

w1: [[-1.17183816  1.83325231  0.56494141]
 [-2.75901842  0.40566692  1.02710688]]
w2: [[-1.13729811]
 [ 1.85547149]
 [ 0.44405553]]


w1: [[-1.17223406  1.83363044  0.56552869]
 [-2.75922775  0.40586531  1.02744901]]
w2: [[-1.1375432 ]
 [ 1.85585403]
 [ 0.44439971]]


w1: [[-1.17259073  1.83397102  0.56605774]
 [-2.75941634  0.40604404  1.02775729]]
w2: [[-1.13776398]
 [ 1.85619867]
 [ 0.44470978]]


w1: [[-1.172912    1.83427787  0.56653434]
 [-2.7595861   0.40620506  1.02803493]]
w2: [[-1.13796282]
 [ 1.85650921]
 [ 0.44498911]]


w1: [[-1.17320144  1.83455431  0.56696367]
 [-2.75973916  0.40635011  1.02828503]]
w2: [[-1.13814199]
 [ 1.85678887]
 [ 0.44524077]]


w1: [[-1.17346215  1.83480334  0.56735045]
 [-2.75987697  0.40648079  1.02851033]]
w2: [[-1.1383034 ]
 [ 1.85704088]
 [ 0.44546747]]


w1: [[-1.17380178  1.83512771  0.56785482]
 [-2.76009679  0.40668926  1.02887082]]
w2: [[-1.13854396]
 [ 1.85737967]
 [ 0.44580185]]


w1: [[-1.17418909  1.83549762  0.56843036]
 [-2.7604088

w2: [[-1.15979707]
 [ 1.88721526]
 [ 0.47560945]]


w1: [[-1.20399868  1.86398578  0.6125868 ]
 [-2.77974367  0.42531317  1.0612756 ]]
w2: [[-1.16002393]
 [ 1.8875649 ]
 [ 0.47593457]]


w1: [[-1.20432293  1.86429584  0.61306643]
 [-2.77991915  0.42547941  1.06156695]]
w2: [[-1.16022825]
 [ 1.88787985]
 [ 0.47622743]]


w1: [[-1.204615    1.86457515  0.61349851]
 [-2.78007722  0.42562917  1.06182945]]
w2: [[-1.16041231]
 [ 1.88816357]
 [ 0.47649124]]


w1: [[-1.20487809  1.86482668  0.61388773]
 [-2.78021955  0.42576405  1.06206584]]
w2: [[-1.16057813]
 [ 1.88841915]
 [ 0.47672889]]


w1: [[-1.20522082  1.86515427  0.61439526]
 [-2.78044677  0.42597926  1.06244397]]
w2: [[-1.16082501]
 [ 1.88876307]
 [ 0.47707856]]


w1: [[-1.20561171  1.86552799  0.61497444]
 [-2.78076935  0.42628479  1.06298089]]
w2: [[-1.16115367]
 [ 1.8891722 ]
 [ 0.4775379 ]]


w1: [[-1.20603693  1.86593461  0.61560494]
 [-2.78118467  0.42667842  1.06367171]]
w2: [[-1.16155922]
 [ 1.88963461]
 [ 0.47809908]]


w1:

w2: [[-1.18589342]
 [ 1.92350018]
 [ 0.5128876 ]]


w1: [[-1.24012792  1.89854479  0.66599011]
 [-2.80382705  0.44812414  1.10157466]]
w2: [[-1.1861794 ]
 [ 1.92389321]
 [ 0.51329923]]


w1: [[-1.2404784   1.89888012  0.66650742]
 [-2.8040657   0.4483501   1.10197628]]
w2: [[-1.18643701]
 [ 1.92424715]
 [ 0.51367003]]


w1: [[-1.24079406  1.8991822   0.66697341]
 [-2.80428076  0.44855362  1.10233808]]
w2: [[-1.18666899]
 [ 1.92456603]
 [ 0.51400399]]


w1: [[-1.2412411   1.89960992  0.66763335]
 [-2.80452895  0.44878849  1.10275614]]
w2: [[-1.18695629]
 [ 1.92500246]
 [ 0.51442426]]


w1: [[-1.24164367  1.89999521  0.66822779]
 [-2.80475235  0.44900006  1.10313272]]
w2: [[-1.18721509]
 [ 1.92539561]
 [ 0.51480281]]


w1: [[-1.2420063   1.90034223  0.66876322]
 [-2.80495358  0.44919062  1.10347199]]
w2: [[-1.18744814]
 [ 1.92574966]
 [ 0.51514381]]


w1: [[-1.24233294  1.90065479  0.66924554]
 [-2.80513477  0.44936228  1.10377753]]
w2: [[-1.18765807]
 [ 1.92606854]
 [ 0.51545095]]


w1:

w2: [[-1.20922172]
 [ 1.95565259]
 [ 0.54675668]]


w1: [[-1.27197564  1.92902565  0.71299398]
 [-2.82540584  0.46854466  1.13809216]]
w2: [[-1.20951295]
 [ 1.95604908]
 [ 0.54718167]]


w1: [[-1.27232754  1.92936254  0.7135129 ]
 [-2.82565022  0.46877584  1.13850713]]
w2: [[-1.20977521]
 [ 1.95640624]
 [ 0.54756445]]


w1: [[-1.27264452  1.92966604  0.71398032]
 [-2.82587028  0.46898407  1.13888097]]
w2: [[-1.21001148]
 [ 1.95672786]
 [ 0.5479092 ]]


w1: [[-1.27309346  1.93009579  0.71464229]
 [-2.82612419  0.46922433  1.13931286]]
w2: [[-1.21030426]
 [ 1.95716774]
 [ 0.54834372]]


w1: [[-1.27349782  1.93048286  0.71523851]
 [-2.82635307  0.46944076  1.13970184]]
w2: [[-1.21056795]
 [ 1.957564  ]
 [ 0.54873514]]


w1: [[-1.273862    1.93083143  0.71577555]
 [-2.82655907  0.4696357   1.1400522 ]]
w2: [[-1.21080542]
 [ 1.95792091]
 [ 0.5490877 ]]


w1: [[-1.27419007  1.93114543  0.71625924]
 [-2.82674479  0.46981126  1.14036787]]
w2: [[-1.21101928]
 [ 1.9582423 ]
 [ 0.54940522]]


w1:

w2: [[-1.2309593 ]
 [ 1.98358965]
 [ 0.57839543]]


w1: [[-1.29876029  1.95465958  0.75255644]
 [-2.84649777  0.48848388  1.17403793]]
w2: [[-1.23126042]
 [ 1.98390889]
 [ 0.57882404]]


w1: [[-1.2990123   1.95490062  0.75293088]
 [-2.84678912  0.4887591   1.17453492]]
w2: [[-1.23153162]
 [ 1.98419642]
 [ 0.5792101 ]]


w1: [[-1.29923928  1.9551177   0.75326812]
 [-2.84705162  0.489007    1.17498255]]
w2: [[-1.23177588]
 [ 1.98445535]
 [ 0.57955778]]


w1: [[-1.29944372  1.95531321  0.75357187]
 [-2.84728813  0.48923028  1.17538571]]
w2: [[-1.23199582]
 [ 1.98468864]
 [ 0.57987094]]


w1: [[-1.2996279   1.95548928  0.75384545]
 [-2.84750104  0.48943138  1.17574883]]
w2: [[-1.23219395]
 [ 1.98489869]
 [ 0.58015299]]


w1: [[-1.29996002  1.95580673  0.75433922]
 [-2.84774995  0.4896664   1.17617369]]
w2: [[-1.23245418]
 [ 1.98524034]
 [ 0.58053535]]


w1: [[-1.30025923  1.95609272  0.75478399]
 [-2.84797406  0.48987809  1.17655635]]
w2: [[-1.23268855]
 [ 1.98554802]
 [ 0.58087975]]


w1:

 [-2.87158465  0.5121398   1.21684575]]
w2: [[-1.25587761]
 [ 2.01311255]
 [ 0.61459494]]


w1: [[-1.32619882  1.98084462  0.79356694]
 [-2.87189865  0.51243544  1.21738219]]
w2: [[-1.2561748 ]
 [ 2.01344419]
 [ 0.6150251 ]]


w1: [[-1.32646751  1.98110068  0.79397047]
 [-2.87218142  0.51270175  1.21786535]]
w2: [[-1.25644243]
 [ 2.01374292]
 [ 0.61541253]]


w1: [[-1.32670951  1.98133135  0.79433393]
 [-2.87243629  0.5129416   1.21830058]]
w2: [[-1.25668347]
 [ 2.01401186]
 [ 0.61576146]]


w1: [[-1.32692742  1.98153901  0.79466128]
 [-2.87266564  0.51315761  1.21869254]]
w2: [[-1.25690055]
 [ 2.01425409]
 [ 0.61607569]]


w1: [[-1.32712376  1.98172605  0.79495609]
 [-2.87287235  0.51335216  1.21904552]]
w2: [[-1.25709605]
 [ 2.01447225]
 [ 0.61635876]]


w1: [[-1.32730055  1.98189449  0.79522163]
 [-2.87305856  0.51352739  1.21936345]]
w2: [[-1.25727212]
 [ 2.0146687 ]
 [ 0.61661369]]


w1: [[-1.32745981  1.98204625  0.79546076]
 [-2.87322617  0.51368523  1.21964979]]
w2: [[-1.257430

w1: [[-1.35714841  2.01030731  0.84012181]
 [-2.8987813   0.53771448  1.26329708]]
w2: [[-1.2828964 ]
 [ 2.04622173]
 [ 0.65441573]]


w1: [[-1.35729754  2.01044917  0.8403464 ]
 [-2.89893937  0.53786296  1.26356661]]
w2: [[-1.28304505]
 [ 2.04638767]
 [ 0.65463239]]


w1: [[-1.35761142  2.01074767  0.84081912]
 [-2.89914417  0.53805524  1.26391613]]
w2: [[-1.28326774]
 [ 2.04670048]
 [ 0.65496969]]


w1: [[-1.35789406  2.01101661  0.84124482]
 [-2.89932847  0.53822845  1.26423085]]
w2: [[-1.28346825]
 [ 2.04698205]
 [ 0.6552735 ]]


w1: [[-1.35814869  2.0112586   0.84162825]
 [-2.89949465  0.53838444  1.26451433]]
w2: [[-1.28364885]
 [ 2.04723573]
 [ 0.65554708]]


w1: [[-1.35837793  2.01147676  0.84197354]
 [-2.89964414  0.53852493  1.26476967]]
w2: [[-1.28381145]
 [ 2.04746413]
 [ 0.65579349]]


w1: [[-1.3585844   2.01167321  0.84228456]
 [-2.89977884  0.53865147  1.26499963]]
w2: [[-1.28395796]
 [ 2.04766989]
 [ 0.6560154 ]]


w1: [[-1.35877037  2.01185012  0.84256464]
 [-2.8999002

w2: [[-1.29658949]
 [ 2.06313229]
 [ 0.67473364]]


w1: [[-1.37343395  2.02578783  0.86465907]
 [-2.91271949  0.55079919  1.28705895]]
w2: [[-1.29677355]
 [ 2.06339025]
 [ 0.67501336]]


w1: [[-1.37366736  2.02600956  0.86501074]
 [-2.91287231  0.55094254  1.2873193 ]]
w2: [[-1.29693937]
 [ 2.06362271]
 [ 0.67526531]]


w1: [[-1.37387753  2.02620935  0.86532742]
 [-2.91300988  0.55107164  1.28755379]]
w2: [[-1.29708862]
 [ 2.06383204]
 [ 0.67549223]]


w1: [[-1.37406683  2.02638912  0.86561263]
 [-2.91313386  0.55118787  1.28776491]]
w2: [[-1.29722309]
 [ 2.0640204 ]
 [ 0.67569655]]


w1: [[-1.37435627  2.02666426  0.86604887]
 [-2.91336465  0.5514043   1.28815818]]
w2: [[-1.29745758]
 [ 2.06432056]
 [ 0.67604733]]


w1: [[-1.37461698  2.02691197  0.86644179]
 [-2.91357231  0.5515992   1.28851235]]
w2: [[-1.2976687 ]
 [ 2.06459093]
 [ 0.67636323]]


w1: [[-1.37493408  2.02721334  0.86691976]
 [-2.91390991  0.55191588  1.28908682]]
w2: [[-1.29798508]
 [ 2.06494427]
 [ 0.67682594]]


w1:


w1: [[-1.39384699  2.04517126  0.8954215 ]
 [-2.93029118  0.56727588  1.3169452 ]]
w2: [[-1.31420815]
 [ 2.08491945]
 [ 0.70097214]]


w1: [[-1.39411294  2.04542375  0.89582229]
 [-2.93050408  0.56747538  1.31730711]]
w2: [[-1.31442392]
 [ 2.08519506]
 [ 0.70129591]]


w1: [[-1.39443648  2.04573083  0.89630973]
 [-2.93084979  0.56779945  1.31789386]]
w2: [[-1.31474686]
 [ 2.08555579]
 [ 0.70176971]]


w1: [[-1.39472783  2.04600739  0.89674872]
 [-2.93116117  0.56809127  1.31842232]]
w2: [[-1.31503773]
 [ 2.08588052]
 [ 0.70219642]]


w1: [[-1.39499021  2.0462563   0.89714408]
 [-2.93144155  0.56835407  1.3188982 ]]
w2: [[-1.31529963]
 [ 2.08617306]
 [ 0.70258069]]


w1: [[-1.39522648  2.04648042  0.89750016]
 [-2.93169403  0.56859076  1.31932676]]
w2: [[-1.31553555]
 [ 2.08643651]
 [ 0.70292675]]


w1: [[-1.39543927  2.04668236  0.89782083]
 [-2.93192148  0.56880391  1.31971276]]
w2: [[-1.31574798]
 [ 2.08667374]
 [ 0.70323843]]


w1: [[-1.39563096  2.04686427  0.89810961]
 [-2.932126

w1: [[-1.40971386  2.0602231   0.91931999]
 [-2.94412184  0.58023226  1.34039688]]
w2: [[-1.32785797]
 [ 2.10168958]
 [ 0.72133505]]


w1: [[-1.40998387  2.06047916  0.91972649]
 [-2.94433856  0.58043528  1.34076428]]
w2: [[-1.3280772 ]
 [ 2.10196924]
 [ 0.72166473]]


w1: [[-1.41031218  2.06079054  0.92022079]
 [-2.9446907   0.58076495  1.34135997]]
w2: [[-1.32840514]
 [ 2.10233545]
 [ 0.72214675]]


w1: [[-1.41060781  2.06107092  0.92066592]
 [-2.9450078   0.58106184  1.34189641]]
w2: [[-1.32870054]
 [ 2.10266519]
 [ 0.72258085]]


w1: [[-1.41087401  2.0613234   0.92106682]
 [-2.94529343  0.58132923  1.34237945]]
w2: [[-1.3289665 ]
 [ 2.10296226]
 [ 0.7229718 ]]


w1: [[-1.41111374  2.06155086  0.92142785]
 [-2.94555068  0.58157003  1.34281456]]
w2: [[-1.32920599]
 [ 2.10322976]
 [ 0.72332388]]


w1: [[-1.41132963  2.06175566  0.92175299]
 [-2.94578242  0.58178687  1.34320641]]
w2: [[-1.32942176]
 [ 2.10347056]
 [ 0.72364092]]


w1: [[-1.41152406  2.06193995  0.92204577]
 [-2.9459910

w2: [[-1.34658873]
 [ 2.12455893]
 [ 0.74930912]]


w1: [[-1.4315114   2.08088207  0.9521113 ]
 [-2.96345496  0.5983218   1.37304425]]
w2: [[-1.34680831]
 [ 2.12480426]
 [ 0.74963242]]


w1: [[-1.43170917  2.08106947  0.95240861]
 [-2.96366811  0.59852105  1.37340295]]
w2: [[-1.34700608]
 [ 2.12502503]
 [ 0.74992359]]


w1: [[-1.43188727  2.08123827  0.95267636]
 [-2.96386003  0.59870046  1.37372601]]
w2: [[-1.34718418]
 [ 2.12522388]
 [ 0.75018579]]


w1: [[-1.43204772  2.08139014  0.95291746]
 [-2.96403289  0.59886205  1.374017  ]]
w2: [[-1.34734452]
 [ 2.12540293]
 [ 0.75042194]]


w1: [[-1.43238568  2.08171034  0.95342523]
 [-2.964257    0.59907156  1.37439454]]
w2: [[-1.3475858 ]
 [ 2.12573862]
 [ 0.75079167]]


w1: [[-1.43269014  2.08199859  0.95388252]
 [-2.9644587   0.59926021  1.37473452]]
w2: [[-1.34780312]
 [ 2.12604094]
 [ 0.75112462]]


w1: [[-1.43296432  2.08225822  0.95429432]
 [-2.96464038  0.59943008  1.37504065]]
w2: [[-1.34799886]
 [ 2.12631321]
 [ 0.75142449]]


w1:

w2: [[-1.36223602]
 [ 2.14569092]
 [ 0.77318579]]


w1: [[-1.45244348  2.10070729  0.98350543]
 [-2.97820377  0.61210781  1.39790332]]
w2: [[-1.36235166]
 [ 2.14584565]
 [ 0.77336228]]


w1: [[-1.45258152  2.10083795  0.98371172]
 [-2.97830343  0.61220104  1.39807177]]
w2: [[-1.36245584]
 [ 2.14598513]
 [ 0.77352124]]


w1: [[-1.45270574  2.10095572  0.98389751]
 [-2.97839332  0.61228496  1.3982234 ]]
w2: [[-1.36254966]
 [ 2.14611077]
 [ 0.77366441]]


w1: [[-1.45281768  2.10106182  0.98406482]
 [-2.97847414  0.61236054  1.39836001]]
w2: [[-1.36263418]
 [ 2.14622378]
 [ 0.77379334]]


w1: [[-1.45311689  2.1013453   0.98451173]
 [-2.97861791  0.61249489  1.39860296]]
w2: [[-1.36281049]
 [ 2.14650464]
 [ 0.77407247]]


w1: [[-1.45338643  2.10160065  0.98491424]
 [-2.97874737  0.61261588  1.39882171]]
w2: [[-1.36296928]
 [ 2.1467576 ]
 [ 0.77432388]]


w1: [[-1.45362914  2.10183072  0.9852767 ]
 [-2.97886395  0.61272484  1.39901876]]
w2: [[-1.36311221]
 [ 2.14698529]
 [ 0.77455026]]


w1:



w1: [[-1.46969402  2.11706209  1.00919139]
 [-2.98894024  0.62214202  1.41604698]]
w2: [[-1.37419629]
 [ 2.16276121]
 [ 0.7916953 ]]


w1: [[-1.46996903  2.11732292  1.00959921]
 [-2.98907375  0.62226677  1.41627276]]
w2: [[-1.37435961]
 [ 2.16301966]
 [ 0.79195416]]


w1: [[-1.47021663  2.11755776  1.00996649]
 [-2.98919392  0.62237912  1.41647613]]
w2: [[-1.37450671]
 [ 2.16325235]
 [ 0.79218727]]


w1: [[-1.47043967  2.11776924  1.01029718]
 [-2.98930216  0.62248033  1.41665924]]
w2: [[-1.37463915]
 [ 2.16346192]
 [ 0.7923972 ]]


w1: [[-1.47064054  2.11795974  1.01059496]
 [-2.98939967  0.62257147  1.4168241 ]]
w2: [[-1.37475836]
 [ 2.16365075]
 [ 0.79258627]]


w1: [[-1.47082138  2.11813116  1.01086318]
 [-2.98948741  0.62265354  1.41697264]]
w2: [[-1.37486577]
 [ 2.16382074]
 [ 0.7927565 ]]


w1: [[-1.47111571  2.11841035  1.01129961]
 [-2.98970294  0.62285489  1.41733682]]
w2: [[-1.37508988]
 [ 2.16411901]
 [ 0.79309881]]


w1: [[-1.47138083  2.11866188  1.01169264]
 [-2.98989

w2: [[-1.3858968 ]
 [ 2.17937136]
 [ 0.80981582]]


w1: [[-1.48687994  2.13337135  1.0345968 ]
 [-2.99971628  0.63221419  1.43427074]]
w2: [[-1.38606453]
 [ 2.17963505]
 [ 0.81008196]]


w1: [[-1.48713231  2.13361096  1.03496838]
 [-2.99984002  0.63232994  1.43448031]]
w2: [[-1.38621557]
 [ 2.17987251]
 [ 0.81032163]]


w1: [[-1.48735952  2.13382673  1.035303  ]
 [-2.9999516   0.63243413  1.43466902]]
w2: [[-1.38635159]
 [ 2.18008637]
 [ 0.81053746]]


w1: [[-1.48756421  2.13402104  1.03560436]
 [-3.00005198  0.63252801  1.43483889]]
w2: [[-1.38647413]
 [ 2.18027902]
 [ 0.81073183]]


w1: [[-1.4877485   2.13419604  1.0358758 ]
 [-3.00014234  0.63261253  1.43499196]]
w2: [[-1.38658452]
 [ 2.18045259]
 [ 0.81090683]]


w1: [[-1.48804855  2.13448095  1.03631747]
 [-3.0003643   0.63281989  1.43536711]]
w2: [[-1.38681471]
 [ 2.18075705]
 [ 0.81125832]]


w1: [[-1.48831868  2.13473749  1.03671515]
 [-3.0005641   0.63300663  1.43570495]]
w2: [[-1.38702202]
 [ 2.18103123]
 [ 0.81157482]]


w1:

w1: [[-1.50498903  2.15057278  1.06117249]
 [-3.01110911  0.64286417  1.45354116]]
w2: [[-1.39861214]
 [ 2.19742203]
 [ 0.82953477]]


w1: [[-1.50529444  2.15086293  1.06161892]
 [-3.01133728  0.64307749  1.45392692]]
w2: [[-1.39884818]
 [ 2.19773269]
 [ 0.82989502]]


w1: [[-1.50556946  2.15112424  1.0620209 ]
 [-3.0115428   0.6432696   1.45427442]]
w2: [[-1.39906073]
 [ 2.19801235]
 [ 0.83021945]]


w1: [[-1.50581706  2.15135956  1.06238294]
 [-3.01172781  0.64344263  1.45458734]]
w2: [[-1.39925218]
 [ 2.19826412]
 [ 0.83051163]]


w1: [[-1.5060401   2.15157151  1.06270897]
 [-3.01189446  0.64359844  1.45486915]]
w2: [[-1.39942455]
 [ 2.19849086]
 [ 0.83077472]]


w1: [[-1.50624096  2.15176249  1.06300259]
 [-3.01204467  0.64373875  1.45512283]]
w2: [[-1.39957976]
 [ 2.19869518]
 [ 0.83101165]]


w1: [[-1.5064218   2.15193439  1.06326699]
 [-3.01217985  0.64386511  1.45535135]]
w2: [[-1.3997196 ]
 [ 2.198879  ]
 [ 0.83122498]]


w1: [[-1.50658464  2.15208912  1.06350505]
 [-3.0123016


w1: [[-1.52962363  2.17399764  1.09701598]
 [-3.02698183  0.65770245  1.48036253]]
w2: [[-1.41595876]
 [ 2.22171974]
 [ 0.85637981]]


w1: [[-1.52993608  2.17429495  1.09746838]
 [-3.02721882  0.65792406  1.4807626 ]]
w2: [[-1.41620278]
 [ 2.22203851]
 [ 0.85675174]]


w1: [[-1.53021753  2.17456269  1.09787571]
 [-3.0274322   0.65812361  1.48112285]]
w2: [[-1.41642261]
 [ 2.22232556]
 [ 0.85708666]]


w1: [[-1.53047097  2.17480373  1.09824252]
 [-3.02762437  0.65830332  1.48144722]]
w2: [[-1.41662049]
 [ 2.22258401]
 [ 0.85738826]]


w1: [[-1.53069913  2.17502093  1.09857285]
 [-3.02779746  0.65846515  1.4817394 ]]
w2: [[-1.41679871]
 [ 2.22281671]
 [ 0.85765988]]


w1: [[-1.53090465  2.17521644  1.09887028]
 [-3.02795339  0.65861088  1.4820025 ]]
w2: [[-1.41695917]
 [ 2.22302628]
 [ 0.85790443]]


w1: [[-1.53108966  2.17539239  1.09913814]
 [-3.02809381  0.65874213  1.48223937]]
w2: [[-1.41710365]
 [ 2.22321486]
 [ 0.85812467]]


w1: [[-1.53125632  2.17555094  1.09937942]
 [-3.028220

w1: [[-1.54736197  2.19088125  1.12261009]
 [-3.03858495  0.66855115  1.49993587]]
w2: [[-1.42858458]
 [ 2.23925781]
 [ 0.87588447]]


w1: [[-1.54755676  2.19106674  1.12289023]
 [-3.03868413  0.66864383  1.500103  ]]
w2: [[-1.4287045 ]
 [ 2.23944211]
 [ 0.87607425]]


w1: [[-1.54787409  2.19136882  1.12334633]
 [-3.03892732  0.66887128  1.50051272]]
w2: [[-1.42895412]
 [ 2.23976612]
 [ 0.87645406]]


w1: [[-1.54815984  2.19164085  1.123757  ]
 [-3.03914642  0.66907609  1.50088167]]
w2: [[-1.42917895]
 [ 2.24005795]
 [ 0.87679607]]


w1: [[-1.54841709  2.19188595  1.12412679]
 [-3.0393436   0.6692605   1.50121391]]
w2: [[-1.42938137]
 [ 2.24032068]
 [ 0.87710404]]


w1: [[-1.54864883  2.19210649  1.12445986]
 [-3.03952122  0.66942656  1.50151312]]
w2: [[-1.42956364]
 [ 2.24055743]
 [ 0.87738138]]


w1: [[-1.54885745  2.19230509  1.12475979]
 [-3.0396812   0.66957611  1.50178254]]
w2: [[-1.42972779]
 [ 2.24077058]
 [ 0.87763113]]


w1: [[-1.54904532  2.1924839   1.1250298 ]
 [-3.0398252

w1: [[-1.56773031  2.21028352  1.15178406]
 [-3.05221796  0.68129849  1.52287543]]
w2: [[-1.44330537]
 [ 2.25947618]
 [ 0.89855558]]


w1: [[-1.5678556   2.21040297  1.151963  ]
 [-3.052315    0.68138927  1.52303851]]
w2: [[-1.44340467]
 [ 2.25960445]
 [ 0.89870638]]


w1: [[-1.56819022  2.21072197  1.15244019]
 [-3.05248737  0.6815505   1.5233283 ]]
w2: [[-1.44361281]
 [ 2.25992131]
 [ 0.8990348 ]]


w1: [[-1.56849158  2.21100926  1.15286994]
 [-3.05264258  0.6816957   1.52358925]]
w2: [[-1.44380021]
 [ 2.2602067 ]
 [ 0.89933056]]


w1: [[-1.5687629   2.21126795  1.15325689]
 [-3.05278254  0.68182647  1.52382433]]
w2: [[-1.44396901]
 [ 2.26046371]
 [ 0.89959687]]


w1: [[-1.56900728  2.21150088  1.15360534]
 [-3.05290842  0.68194419  1.52403593]]
w2: [[-1.444121  ]
 [ 2.26069522]
 [ 0.89983672]]


w1: [[-1.56922734  2.21171069  1.1539191 ]
 [-3.05302191  0.68205023  1.52422655]]
w2: [[-1.44425786]
 [ 2.2609036 ]
 [ 0.90005267]]


w1: [[-1.56942546  2.21189952  1.15420163]
 [-3.0531239

w2: [[-1.45577919]
 [ 2.27560425]
 [ 0.9174878 ]]


w1: [[-1.58360934  2.22541809  1.17438924]
 [-3.06449699  0.69277942  1.54346681]]
w2: [[-1.45587718]
 [ 2.27571321]
 [ 0.9176318 ]]


w1: [[-1.58369708  2.22550178  1.17451417]
 [-3.06459332  0.69286954  1.5436281 ]]
w2: [[-1.4559654]
 [ 2.2758112]
 [ 0.9177615]]


w1: [[-1.58377612  2.22557712  1.17462671]
 [-3.0646801   0.69295073  1.54377329]]
w2: [[-1.45604479]
 [ 2.27589941]
 [ 0.91787827]]


w1: [[-1.58384728  2.22564483  1.17472804]
 [-3.0647583   0.6930238   1.54390407]]
w2: [[-1.45611632]
 [ 2.27597904]
 [ 0.91798341]]


w1: [[-1.5839113   2.22570586  1.17481923]
 [-3.06482863  0.6930896   1.54402184]]
w2: [[-1.45618069]
 [ 2.27605057]
 [ 0.91807812]]


w1: [[-1.583969    2.22576094  1.17490137]
 [-3.06489205  0.69314885  1.54412794]]
w2: [[-1.45623875]
 [ 2.27611518]
 [ 0.91816342]]


w1: [[-1.58402097  2.22581053  1.1749754 ]
 [-3.06494904  0.6932022   1.54422343]]
w2: [[-1.45629096]
 [ 2.27617335]
 [ 0.91824019]]


w1: [[


w1: [[-1.59141362  2.23285079  1.18550777]
 [-3.07309318  0.70081288  1.55779111]]
w2: [[-1.46373081]
 [ 2.2844398 ]
 [ 0.92916524]]


w1: [[-1.59147942  2.23291349  1.18560159]
 [-3.07316566  0.70088059  1.55791152]]
w2: [[-1.46379697]
 [ 2.28451347]
 [ 0.9292624 ]]


w1: [[-1.59153867  2.23297     1.18568599]
 [-3.07323098  0.70094156  1.55802   ]]
w2: [[-1.46385658]
 [ 2.28457975]
 [ 0.92934984]]


w1: [[-1.59159207  2.23302078  1.18576205]
 [-3.07328987  0.70099646  1.55811763]]
w2: [[-1.46391022]
 [ 2.28463936]
 [ 0.92942858]]


w1: [[-1.59164011  2.23306656  1.18583047]
 [-3.0733428   0.70104593  1.5582056 ]]
w2: [[-1.4639585 ]
 [ 2.284693  ]
 [ 0.92949951]]


w1: [[-1.59168339  2.23310781  1.18589211]
 [-3.07339048  0.70109046  1.55828476]]
w2: [[-1.46400201]
 [ 2.2847414 ]
 [ 0.9295634 ]]


w1: [[-1.59172237  2.233145    1.18594766]
 [-3.0734334   0.70113057  1.55835605]]
w2: [[-1.46404123]
 [ 2.28478503]
 [ 0.92962092]]


w1: [[-1.59191132  2.23332477  1.18621683]
 [-3.073641



w1: [[-1.59973371  2.24076796  1.19736409]
 [-3.0822494   0.70936447  1.57293606]]
w2: [[-1.47208929]
 [ 2.29373121]
 [ 0.94141519]]


w1: [[-1.59990931  2.24093485  1.19761419]
 [-3.08244228  0.70954466  1.57325387]]
w2: [[-1.47226536]
 [ 2.29392719]
 [ 0.94167298]]


w1: [[-1.60006738  2.24108505  1.19783938]
 [-3.08261609  0.7097069   1.57354009]]
w2: [[-1.47242391]
 [ 2.29410362]
 [ 0.94190514]]


w1: [[-1.60020971  2.24122047  1.19804215]
 [-3.08277249  0.70985299  1.57379782]]
w2: [[-1.47256672]
 [ 2.29426241]
 [ 0.94211417]]


w1: [[-1.60033786  2.24134231  1.19822478]
 [-3.0829134   0.7099846   1.57402992]]
w2: [[-1.47269535]
 [ 2.29440546]
 [ 0.94230241]]


w1: [[-1.60045326  2.24145198  1.19838929]
 [-3.08304024  0.71010309  1.5742389 ]]
w2: [[-1.4728111 ]
 [ 2.29453421]
 [ 0.94247192]]


w1: [[-1.60055721  2.24155092  1.19853735]
 [-3.08315444  0.71020979  1.57442713]]
w2: [[-1.47291541]
 [ 2.29465008]
 [ 0.94262457]]


w1: [[-1.60065079  2.24163985  1.19867074]
 [-3.08325


w1: [[-1.60734248  2.24799943  1.20820487]
 [-3.09060979  0.71716917  1.58666408]]
w2: [[-1.47971666]
 [ 2.30221581]
 [ 0.95257092]]


w1: [[-1.60740554  2.24805927  1.20829475]
 [-3.09067893  0.71723378  1.58677745]]
w2: [[-1.47977984]
 [ 2.30228615]
 [ 0.95266318]]


w1: [[-1.60746229  2.24811316  1.20837569]
 [-3.0907414   0.71729195  1.58687949]]
w2: [[-1.4798367 ]
 [ 2.30234933]
 [ 0.95274627]]


w1: [[-1.60751343  2.24816179  1.20844853]
 [-3.09079766  0.71734434  1.5869714 ]]
w2: [[-1.47988796]
 [ 2.30240631]
 [ 0.95282114]]


w1: [[-1.60755944  2.24820566  1.20851409]
 [-3.09084821  0.71739155  1.58705413]]
w2: [[-1.4799341 ]
 [ 2.30245757]
 [ 0.95288855]]


w1: [[-1.60760093  2.248245    1.2085731 ]
 [-3.09089375  0.71743405  1.58712864]]
w2: [[-1.47997558]
 [ 2.30250382]
 [ 0.95294923]]


w1: [[-1.60780191  2.24843597  1.20885932]
 [-3.09111428  0.71763992  1.58748925]]
w2: [[-1.48017681]
 [ 2.3027277 ]
 [ 0.95324308]]


w1: [[-1.60798287  2.24860787  1.20911705]
 [-3.091312

 [ 0.96319634]]


w1: [[-1.61478579  2.25506973  1.21880496]
 [-3.0987761   0.72479063  1.59998   ]]
w2: [[-1.48716414]
 [ 2.31050658]
 [ 0.96343946]]


w1: [[-1.61493599  2.25521231  1.21901894]
 [-3.09894085  0.72494435  1.60024762]]
w2: [[-1.48731434]
 [ 2.31067371]
 [ 0.96365839]]


w1: [[-1.6150713   2.25534081  1.21921158]
 [-3.09908915  0.72508276  1.60048866]]
w2: [[-1.48744965]
 [ 2.31082439]
 [ 0.9638555 ]]


w1: [[-1.61519313  2.25545645  1.21938503]
 [-3.09922266  0.72520739  1.60070562]]
w2: [[-1.48757148]
 [ 2.31096005]
 [ 0.96403301]]


w1: [[-1.6153028   2.25556064  1.21954119]
 [-3.09934306  0.72531962  1.60090101]]
w2: [[-1.48768115]
 [ 2.31108212]
 [ 0.96419287]]


w1: [[-1.61540163  2.25565434  1.21968186]
 [-3.0994513   0.72542071  1.60107696]]
w2: [[-1.48777986]
 [ 2.31119204]
 [ 0.96433681]]


w1: [[-1.61549056  2.25573874  1.21980846]
 [-3.09954882  0.72551173  1.60123539]]
w2: [[-1.48786879]
 [ 2.31129098]
 [ 0.96446645]]


w1: [[-1.61557066  2.25581479  1.2199



w1: [[-1.6217376   2.26166773  1.22869909]
 [-3.10639405  0.73189688  1.61231613]]
w2: [[-1.4941082 ]
 [ 2.31823945]
 [ 0.97354972]]


w1: [[-1.62187612  2.2617991   1.22889614]
 [-3.10654569  0.73203832  1.61256087]]
w2: [[-1.49424636]
 [ 2.31839347]
 [ 0.97375071]]


w1: [[-1.62200081  2.26191735  1.22907352]
 [-3.1066823   0.73216569  1.61278129]]
w2: [[-1.49437082]
 [ 2.31853199]
 [ 0.97393173]]


w1: [[-1.62211311  2.26202393  1.22923326]
 [-3.10680532  0.73228037  1.61297977]]
w2: [[-1.49448287]
 [ 2.31865692]
 [ 0.97409469]]


w1: [[-1.6222142   2.26211977  1.22937715]
 [-3.10691595  0.73238367  1.61315846]]
w2: [[-1.49458385]
 [ 2.31876945]
 [ 0.97424144]]


w1: [[-1.62230527  2.26220608  1.22950673]
 [-3.10701561  0.73247665  1.6133194 ]]
w2: [[-1.49467468]
 [ 2.31887078]
 [ 0.97437358]]


w1: [[-1.62238729  2.2622838   1.22962344]
 [-3.10710549  0.7325604   1.61346436]]
w2: [[-1.49475646]
 [ 2.31896186]
 [ 0.97449261]]


w1: [[-1.62246108  2.2623539   1.22972846]
 [-3.10718

w1: [[-1.63095224  2.27040625  1.24180007]
 [-3.11647677  0.74129933  1.6285181 ]]
w2: [[-1.50329471]
 [ 2.32847524]
 [ 0.9868893 ]]


w1: [[-1.63104594  2.27049494  1.24193311]
 [-3.11657929  0.74139482  1.62868202]]
w2: [[-1.50338805]
 [ 2.32857919]
 [ 0.98702455]]


w1: [[-1.63113034  2.27057481  1.24205291]
 [-3.11667156  0.74148083  1.6288296 ]]
w2: [[-1.50347209]
 [ 2.32867289]
 [ 0.98714638]]


w1: [[-1.63120627  2.27064681  1.2421608 ]
 [-3.11675453  0.74155825  1.62896252]]
w2: [[-1.50354779]
 [ 2.32875729]
 [ 0.98725605]]


w1: [[-1.6312747   2.27071166  1.24225795]
 [-3.1168294   0.74162799  1.6290822 ]]
w2: [[-1.50361586]
 [ 2.3288331 ]
 [ 0.98735482]]


w1: [[-1.63133633  2.27077007  1.24234545]
 [-3.11689663  0.74169075  1.62918997]]
w2: [[-1.50367725]
 [ 2.32890153]
 [ 0.98744375]]


w1: [[-1.63139176  2.27082276  1.24242425]
 [-3.11695719  0.74174732  1.629287  ]]
w2: [[-1.50373244]
 [ 2.32896304]
 [ 0.98752385]]


w1: [[-1.63144171  2.27087021  1.24249518]
 [-3.1170117

w2: [[-1.51249397]
 [ 2.33872962]
 [ 1.00020254]]


w1: [[-1.6402688   2.27923632  1.25502551]
 [-3.12665415  0.75078648  1.64472651]]
w2: [[-1.51256382]
 [ 2.33880758]
 [ 1.00030351]]


w1: [[-1.6403321   2.2792964   1.25511527]
 [-3.12672329  0.75085092  1.64483619]]
w2: [[-1.51262677]
 [ 2.33887768]
 [ 1.00039446]]


w1: [[-1.64038908  2.27935052  1.25519609]
 [-3.12678552  0.75090891  1.64493489]]
w2: [[-1.51268339]
 [ 2.33894086]
 [ 1.00047636]]


w1: [[-1.64044046  2.27939916  1.25526893]
 [-3.12684155  0.75096112  1.64502382]]
w2: [[-1.51273441]
 [ 2.33899784]
 [ 1.00055015]]


w1: [[-1.64048672  2.27944303  1.2553345 ]
 [-3.12689209  0.75100815  1.64510393]]
w2: [[-1.51278031]
 [ 2.3390491 ]
 [ 1.00061655]]


w1: [[-1.64071071  2.27965522  1.25565207]
 [-3.12713647  0.7512359   1.64549088]]
w2: [[-1.51300287]
 [ 2.33929729]
 [ 1.00093794]]


w1: [[-1.64091241  2.27984619  1.25593805]
 [-3.12735653  0.751441    1.64583933]]
w2: [[-1.51320326]
 [ 2.33952069]
 [ 1.00122726]]


w1:

w1: [[-1.65649736  2.29460025  1.27800107]
 [-3.14433956  0.76726657  1.67254579]]
w2: [[-1.52866399]
 [ 2.35676408]
 [ 1.02348924]]


w1: [[-1.65662193  2.29471803  1.27817702]
 [-3.14447498  0.76739287  1.67275739]]
w2: [[-1.52878737]
 [ 2.35690165]
 [ 1.02366626]]


w1: [[-1.65673411  2.29482412  1.27833545]
 [-3.14459705  0.7675066   1.67294788]]
w2: [[-1.52889848]
 [ 2.35702562]
 [ 1.02382576]]


w1: [[-1.65683508  2.29491973  1.27847815]
 [-3.14470696  0.767609    1.67311943]]
w2: [[-1.52899849]
 [ 2.3571372 ]
 [ 1.02396929]]


w1: [[-1.65692604  2.2950058   1.27860665]
 [-3.14480591  0.76770121  1.67327392]]
w2: [[-1.52908862]
 [ 2.35723758]
 [ 1.02409863]]


w1: [[-1.65700793  2.29508328  1.27872241]
 [-3.14489508  0.76778424  1.67341304]]
w2: [[-1.52916968]
 [ 2.35732818]
 [ 1.0242151 ]]


w1: [[-1.65708172  2.29515314  1.27882659]
 [-3.14497542  0.76785898  1.67353833]]
w2: [[-1.52924275]
 [ 2.35740972]
 [ 1.02431989]]


w1: [[-1.65714812  2.29521608  1.27892041]
 [-3.1450476

w2: [[-1.54003251]
 [ 2.36944842]
 [ 1.03976619]]


w1: [[-1.66813231  2.30560374  1.29441357]
 [-3.15698504  0.77904791  1.69217169]]
w2: [[-1.54017341]
 [ 2.36960578]
 [ 1.03996742]]


w1: [[-1.66826069  2.3057251   1.29459441]
 [-3.15712452  0.77917778  1.69238687]]
w2: [[-1.54030025]
 [ 2.3697474 ]
 [ 1.04014862]]


w1: [[-1.66837633  2.30583429  1.29475725]
 [-3.15725017  0.77929473  1.6925807 ]]
w2: [[-1.54041445]
 [ 2.36987495]
 [ 1.04031181]]


w1: [[-1.6684804   2.30593276  1.29490387]
 [-3.15736318  0.77940005  1.69275522]]
w2: [[-1.54051733]
 [ 2.36998987]
 [ 1.0404588 ]]


w1: [[-1.66857421  2.30602145  1.29503596]
 [-3.15746498  0.77949488  1.69291234]]
w2: [[-1.54060996]
 [ 2.37009335]
 [ 1.04059112]]


w1: [[-1.66865861  2.30610132  1.29515481]
 [-3.15755677  0.7795803   1.69305384]]
w2: [[-1.5406934 ]
 [ 2.37018633]
 [ 1.04071021]]


w1: [[-1.66873467  2.30617309  1.29526186]
 [-3.15763927  0.77965719  1.69318128]]
w2: [[-1.5407685 ]
 [ 2.37027025]
 [ 1.0408175 ]]


w1:

w2: [[-1.55152035]
 [ 2.38227034]
 [ 1.05613124]]


w1: [[-1.67981088  2.31663918  1.31083095]
 [-3.16965199  0.79084587  1.71160853]]
w2: [[-1.55169892]
 [ 2.38246965]
 [ 1.05638492]]


w1: [[-1.67997396  2.3167932   1.31105983]
 [-3.16982865  0.79101044  1.71187806]]
w2: [[-1.55185974]
 [ 2.38264918]
 [ 1.05661333]]


w1: [[-1.68012083  2.31693196  1.31126595]
 [-3.16998768  0.79115862  1.71212077]]
w2: [[-1.55200446]
 [ 2.38281083]
 [ 1.05681896]]


w1: [[-1.68025303  2.31705689  1.31145144]
 [-3.17013097  0.79129207  1.7123394 ]]
w2: [[-1.55213487]
 [ 2.38295627]
 [ 1.05700421]]


w1: [[-1.68037212  2.31716943  1.31161857]
 [-3.17025995  0.79141223  1.71253622]]
w2: [[-1.55225229]
 [ 2.3830874 ]
 [ 1.05717099]]


w1: [[-1.68047941  2.31727076  1.31176901]
 [-3.17037606  0.79152042  1.71271348]]
w2: [[-1.55235803]
 [ 2.38320541]
 [ 1.05732119]]


w1: [[-1.68057597  2.31736207  1.31190443]
 [-3.17048073  0.79161787  1.7128731 ]]
w2: [[-1.55245316]
 [ 2.38331175]
 [ 1.05745637]]


w1:

w2: [[-1.56273305]
 [ 2.39478612]
 [ 1.07202029]]


w1: [[-1.69108796  2.32728887  1.32662249]
 [-3.18185687  0.80221301  1.73013198]]
w2: [[-1.5628041 ]
 [ 2.39486551]
 [ 1.07212067]]


w1: [[-1.69115293  2.32735014  1.32671332]
 [-3.1819272   0.80227846  1.7302382 ]]
w2: [[-1.56286812]
 [ 2.3949368 ]
 [ 1.07221115]]


w1: [[-1.69121146  2.32740545  1.32679522]
 [-3.18199062  0.80233741  1.73033381]]
w2: [[-1.5629257 ]
 [ 2.39500117]
 [ 1.07229257]]


w1: [[-1.69126415  2.32745528  1.32686889]
 [-3.18204761  0.80239052  1.73041987]]
w2: [[-1.56297755]
 [ 2.39505911]
 [ 1.07236588]]


w1: [[-1.69151938  2.32769632  1.32722545]
 [-3.18232346  0.80264747  1.7308358 ]]
w2: [[-1.56322861]
 [ 2.39533925]
 [ 1.07272041]]


w1: [[-1.69174922  2.32791328  1.32754648]
 [-3.18257189  0.80287886  1.73121035]]
w2: [[-1.56345463]
 [ 2.3955915 ]
 [ 1.07303965]]


w1: [[-1.69195616  2.32810855  1.32783556]
 [-3.18279552  0.80308717  1.73154759]]
w2: [[-1.56365812]
 [ 2.39581871]
 [ 1.07332718]]


w1:

w2: [[-1.57380605]
 [ 2.40714574]
 [ 1.08762813]]


w1: [[-1.70249474  2.33805418  1.34252989]
 [-3.19417667  0.81368703  1.7486285 ]]
w2: [[-1.57401395]
 [ 2.40737772]
 [ 1.08792031]]


w1: [[-1.70268548  2.33823419  1.34279513]
 [-3.19438243  0.8138786   1.74893558]]
w2: [[-1.57420111]
 [ 2.40758657]
 [ 1.0881834 ]]


w1: [[-1.70285714  2.33839607  1.34303403]
 [-3.19456768  0.81405109  1.74921215]]
w2: [[-1.57436967]
 [ 2.40777469]
 [ 1.08842027]]


w1: [[-1.70301175  2.33854198  1.34324908]
 [-3.19473457  0.81420642  1.74946117]]
w2: [[-1.57452142]
 [ 2.4079442 ]
 [ 1.08863354]]


w1: [[-1.70315099  2.33867335  1.3434428 ]
 [-3.19488478  0.81434631  1.74968541]]
w2: [[-1.57465804]
 [ 2.40809679]
 [ 1.08882558]]


w1: [[-1.7032764   2.33879161  1.3436172 ]
 [-3.19501996  0.81447226  1.74988735]]
w2: [[-1.57478106]
 [ 2.40823412]
 [ 1.08899856]]


w1: [[-1.70338929  2.33889818  1.3437742 ]
 [-3.19514179  0.81458569  1.75006914]]
w2: [[-1.57489192]
 [ 2.40835786]
 [ 1.08915424]]


w1:

w2: [[-1.5836966 ]
 [ 2.41818428]
 [ 1.10149717]]


w1: [[-1.71243417  2.34742999  1.35633242]
 [-3.20489144  0.82366568  1.76455462]]
w2: [[-1.58376324]
 [ 2.41825867]
 [ 1.10159051]]


w1: [[-1.71249545  2.34748769  1.3564173 ]
 [-3.20495749  0.82372713  1.76465237]]
w2: [[-1.58382332]
 [ 2.41832566]
 [ 1.10167456]]


w1: [[-1.71255064  2.34753966  1.35649383]
 [-3.20501685  0.82378244  1.76474035]]
w2: [[-1.58387744]
 [ 2.41838598]
 [ 1.10175025]]


w1: [[-1.71281767  2.34779143  1.35686374]
 [-3.20530438  0.82405025  1.76516521]]
w2: [[-1.58413911]
 [ 2.41867805]
 [ 1.10211599]]


w1: [[-1.71305811  2.34801817  1.35719681]
 [-3.20556331  0.82429141  1.76554787]]
w2: [[-1.58437467]
 [ 2.41894102]
 [ 1.10244536]]


w1: [[-1.7132746   2.34822226  1.35749674]
 [-3.20579648  0.82450855  1.76589239]]
w2: [[-1.58458686]
 [ 2.41917777]
 [ 1.10274196]]


w1: [[-1.71346951  2.34840608  1.35776675]
 [-3.20600653  0.82470405  1.76620257]]
w2: [[-1.58477795]
 [ 2.41939092]
 [ 1.10300899]]


w1:

w2: [[-1.59491765]
 [ 2.43070626]
 [ 1.11714756]]


w1: [[-1.72407174  2.35840034  1.37242138]
 [-3.21741152  0.83532763  1.78297806]]
w2: [[-1.59515798]
 [ 2.43097448]
 [ 1.11748159]]


w1: [[-1.72429299  2.35860896  1.37272644]
 [-3.21764922  0.83554906  1.78332579]]
w2: [[-1.59537435]
 [ 2.431216  ]
 [ 1.11778235]]


w1: [[-1.72449219  2.35879683  1.3730011 ]
 [-3.21786332  0.83574849  1.78363895]]
w2: [[-1.59556925]
 [ 2.43143344]
 [ 1.1180532 ]]


w1: [[-1.7246716   2.35896587  1.37324846]
 [-3.2180562   0.83592808  1.783921  ]]
w2: [[-1.59574473]
 [ 2.43162918]
 [ 1.1182971 ]]


w1: [[-1.72483313  2.35911822  1.37347114]
 [-3.21822977  0.83608979  1.78417492]]
w2: [[-1.59590268]
 [ 2.43180537]
 [ 1.11851668]]


w1: [[-1.72497857  2.35925531  1.37367165]
 [-3.21838617  0.8362354   1.78440356]]
w2: [[-1.5960449 ]
 [ 2.43196416]
 [ 1.11871445]]


w1: [[-1.72510958  2.35937881  1.37385225]
 [-3.21852684  0.83636653  1.78460944]]
w2: [[-1.59617305]
 [ 2.43210721]
 [ 1.11889255]]


w1:

 [ 1.13355458]]


w1: [[-1.73609853  2.36973596  1.3889637 ]
 [-3.23032522  0.8473562   1.80177486]]
w2: [[-1.60691249]
 [ 2.44408798]
 [ 1.13377714]]


w1: [[-1.73624706  2.36987591  1.38916743]
 [-3.23048449  0.84750462  1.80200553]]
w2: [[-1.60705745]
 [ 2.44424963]
 [ 1.13397753]]


w1: [[-1.73638082  2.37000203  1.38935089]
 [-3.23062801  0.84763825  1.80221319]]
w2: [[-1.60718799]
 [ 2.4443953 ]
 [ 1.13415802]]


w1: [[-1.73650122  2.37011552  1.38951612]
 [-3.23075724  0.84775859  1.80240023]]
w2: [[-1.60730553]
 [ 2.44452643]
 [ 1.1343205 ]]


w1: [[-1.7366097   2.3702178   1.38966489]
 [-3.23087358  0.84786695  1.80256867]]
w2: [[-1.60741138]
 [ 2.44464445]
 [ 1.13446689]]


w1: [[-1.73670733  2.37030983  1.38979888]
 [-3.23097825  0.84796453  1.80272031]]
w2: [[-1.60750675]
 [ 2.44475079]
 [ 1.13459861]]


w1: [[-1.73679531  2.37039256  1.38991952]
 [-3.23107266  0.84805238  1.8028568 ]]
w2: [[-1.60759258]
 [ 2.44484663]
 [ 1.13471723]]


w1: [[-1.73687446  2.37046719  1.3900

w2: [[-1.61647379]
 [ 2.45475149]
 [ 1.14695895]]


w1: [[-1.74598753  2.37905288  1.40249813]
 [-3.24092221  0.85722917  1.81704938]]
w2: [[-1.61656094]
 [ 2.45484877]
 [ 1.14707887]]


w1: [[-1.746068    2.37912869  1.40260804]
 [-3.24100828  0.85730946  1.81717312]]
w2: [[-1.61663938]
 [ 2.45493627]
 [ 1.14718676]]


w1: [[-1.74614048  2.37919688  1.40270698]
 [-3.24108577  0.85738176  1.81728458]]
w2: [[-1.61671007]
 [ 2.45501494]
 [ 1.14728391]]


w1: [[-1.74620569  2.37925839  1.40279615]
 [-3.24115562  0.85744685  1.81738496]]
w2: [[-1.61677372]
 [ 2.45508599]
 [ 1.14737141]]


w1: [[-1.74626446  2.37931371  1.40287638]
 [-3.24121857  0.85750544  1.81747532]]
w2: [[-1.61683106]
 [ 2.45514989]
 [ 1.14745021]]


w1: [[-1.74654877  2.37958145  1.40326428]
 [-3.24152279  0.85778898  1.81791139]]
w2: [[-1.61710811]
 [ 2.45545888]
 [ 1.14783096]]


w1: [[-1.74680471  2.37982249  1.40361357]
 [-3.24179673  0.85804427  1.81830406]]
w2: [[-1.61735761]
 [ 2.45573711]
 [ 1.14817381]]


w1:

w1: [[-1.75540924  2.38792658  1.41533577]
 [-3.2510016   0.86662149  1.83145416]]
w2: [[-1.62574136]
 [ 2.46508384]
 [ 1.15967143]]


w1: [[-1.75548279  2.38799596  1.41543591]
 [-3.25108027  0.86669481  1.83156621]]
w2: [[-1.62581301]
 [ 2.46516371]
 [ 1.15976954]]


w1: [[-1.75554907  2.38805842  1.41552603]
 [-3.25115108  0.86676085  1.83166718]]
w2: [[-1.6258775 ]
 [ 2.46523571]
 [ 1.15985787]]


w1: [[-1.7556088   2.38811469  1.41560721]
 [-3.25121498  0.86682034  1.83175802]]
w2: [[-1.62593567]
 [ 2.46530056]
 [ 1.15993738]]


w1: [[-1.75589752  2.38838673  1.41599953]
 [-3.25152349  0.86710793  1.83219671]]
w2: [[-1.62621677]
 [ 2.46561384]
 [ 1.16032183]]


w1: [[-1.75615752  2.38863158  1.41635275]
 [-3.25180125  0.86736691  1.83259177]]
w2: [[-1.62646985]
 [ 2.46589589]
 [ 1.16066802]]


w1: [[-1.75639164  2.38885212  1.4166708 ]
 [-3.25205135  0.86760008  1.83294749]]
w2: [[-1.62669778]
 [ 2.46615005]
 [ 1.16097975]]


w1: [[-1.75660253  2.38905072  1.41695726]
 [-3.2522766

w1: [[-1.76461864  2.39660048  1.42782819]
 [-3.2608366   0.8757897   1.84539902]]
w2: [[-1.63470304]
 [ 2.47507286]
 [ 1.17190576]]


w1: [[-1.76472104  2.39669681  1.42796683]
 [-3.2609458   0.87589157  1.8455534 ]]
w2: [[-1.63480258]
 [ 2.47518373]
 [ 1.17204142]]


w1: [[-1.76481318  2.39678359  1.42809165]
 [-3.26104426  0.8759833   1.8456924 ]]
w2: [[-1.63489223]
 [ 2.47528362]
 [ 1.17216361]]


w1: [[-1.76489615  2.39686179  1.42820406]
 [-3.26113296  0.87606591  1.84581757]]
w2: [[-1.63497293]
 [ 2.47537351]
 [ 1.17227364]]


w1: [[-1.7649709   2.39693213  1.42830527]
 [-3.26121283  0.8761403   1.84593034]]
w2: [[-1.63504565]
 [ 2.47545457]
 [ 1.1723727 ]]


w1: [[-1.76503825  2.39699554  1.42839634]
 [-3.26128459  0.87620723  1.84603179]]
w2: [[-1.63511109]
 [ 2.47552752]
 [ 1.17246187]]


w1: [[-1.76509881  2.39705253  1.42847836]
 [-3.2613492   0.87626755  1.84612322]]
w2: [[-1.63516998]
 [ 2.47559309]
 [ 1.17254221]]


w1: [[-1.76539195  2.39732862  1.42887485]
 [-3.2616620

w1: [[-1.78346384  2.41434407  1.45321846]
 [-3.2809155   0.89451271  1.87353146]]
w2: [[-1.6530087 ]
 [ 2.49546313]
 [ 1.19671381]]


w1: [[-1.78362417  2.41449499  1.45343351]
 [-3.28108621  0.89467186  1.87376869]]
w2: [[-1.65316427]
 [ 2.49563646]
 [ 1.19692361]]


w1: [[-1.78376853  2.41463089  1.45362723]
 [-3.28123975  0.89481515  1.87398231]]
w2: [[-1.65330434]
 [ 2.49579239]
 [ 1.19711256]]


w1: [[-1.78389859  2.4147532   1.45380163]
 [-3.28137803  0.89494419  1.87417459]]
w2: [[-1.65343046]
 [ 2.49593282]
 [ 1.19728267]]


w1: [[-1.78401566  2.41486335  1.45395863]
 [-3.28150249  0.89506036  1.87434781]]
w2: [[-1.65354407]
 [ 2.49605918]
 [ 1.19743586]]


w1: [[-1.78412104  2.41496253  1.45410001]
 [-3.28161454  0.89516497  1.87450373]]
w2: [[-1.65364635]
 [ 2.49617314]
 [ 1.19757378]]


w1: [[-1.78421593  2.41505194  1.45422733]
 [-3.28171563  0.89525914  1.87464416]]
w2: [[-1.6537385 ]
 [ 2.49627566]
 [ 1.197698  ]]


w1: [[-1.7843014   2.41513252  1.45434201]
 [-3.2818064

w2: [[-1.66557467]
 [ 2.50944853]
 [ 1.21360254]]


w1: [[-1.79653275  2.42664599  1.47068763]
 [-3.2948029   0.90746939  1.89273596]]
w2: [[-1.66567862]
 [ 2.50956416]
 [ 1.2137419 ]]


w1: [[-1.79662931  2.42673683  1.47081637]
 [-3.29490542  0.90756512  1.8928771 ]]
w2: [[-1.6657722 ]
 [ 2.50966835]
 [ 1.21386731]]


w1: [[-1.79671633  2.42681861  1.47093236]
 [-3.29499769  0.90765131  1.89300418]]
w2: [[-1.66585648]
 [ 2.50976205]
 [ 1.2139802 ]]


w1: [[-1.79679465  2.42689228  1.47103679]
 [-3.2950809   0.90772891  1.89311862]]
w2: [[-1.66593242]
 [ 2.50984645]
 [ 1.21408188]]


w1: [[-1.79686522  2.42695856  1.47113085]
 [-3.29515576  0.90779877  1.89322174]]
w2: [[-1.66600072]
 [ 2.5099225 ]
 [ 1.21417344]]


w1: [[-1.79692876  2.4270184   1.47121549]
 [-3.29522324  0.90786171  1.8933146 ]]
w2: [[-1.66606224]
 [ 2.50999093]
 [ 1.21425593]]


w1: [[-1.79723597  2.42730761  1.47162449]
 [-3.29554939  0.90816593  1.89376247]]
w2: [[-1.66635978]
 [ 2.51032186]
 [ 1.21465409]]


w1:

w2: [[-1.67808449]
 [ 2.52336049]
 [ 1.2303015 ]]


w1: [[-1.80942607  2.4387815   1.48781037]
 [-3.30847597  0.92023098  1.91144824]]
w2: [[-1.67816162]
 [ 2.52344608]
 [ 1.23040414]]


w1: [[-1.80949783  2.43884897  1.48790538]
 [-3.30855203  0.92030197  1.91155183]]
w2: [[-1.678231  ]
 [ 2.52352333]
 [ 1.23049653]]


w1: [[-1.80956244  2.43890977  1.48799098]
 [-3.30862045  0.92036587  1.91164517]]
w2: [[-1.67829347]
 [ 2.52359271]
 [ 1.23057973]]


w1: [[-1.80987489  2.43920374  1.48840427]
 [-3.30895138  0.9206748   1.91209519]]
w2: [[-1.67859566]
 [ 2.52392864]
 [ 1.23098147]]


w1: [[-1.81015623  2.43946862  1.48877645]
 [-3.3092494   0.92095298  1.9125005 ]]
w2: [[-1.67886782]
 [ 2.5242312 ]
 [ 1.23134327]]


w1: [[-1.81040955  2.43970704  1.48911154]
 [-3.30951762  0.92120349  1.9128654 ]]
w2: [[-1.67911291]
 [ 2.52450371]
 [ 1.23166907]]


w1: [[-1.81063771  2.43992186  1.48941326]
 [-3.30975914  0.92142904  1.91319406]]
w2: [[-1.67933357]
 [ 2.52474904]
 [ 1.23196244]]


w1:

 [-3.32214522  0.93299508  1.92996871]]
w2: [[-1.69064951]
 [ 2.53732371]
 [ 1.24696243]]


w1: [[-1.82240868  2.45100117  1.50493717]
 [-3.3222146   0.93305993  1.93006241]]
w2: [[-1.69071293]
 [ 2.53739429]
 [ 1.24704635]]


w1: [[-1.82272625  2.45130014  1.5053544 ]
 [-3.3225503   0.93337345  1.93051445]]
w2: [[-1.69101965]
 [ 2.53773499]
 [ 1.24745142]]


w1: [[-1.82301223  2.45156932  1.50573015]
 [-3.32285261  0.93365574  1.93092155]]
w2: [[-1.69129586]
 [ 2.53804183]
 [ 1.24781621]]


w1: [[-1.82326972  2.45181155  1.50606847]
 [-3.32312489  0.93390995  1.93128812]]
w2: [[-1.69154453]
 [ 2.53831816]
 [ 1.24814475]]


w1: [[-1.82350159  2.45202971  1.50637317]
 [-3.32336998  0.93413883  1.93161821]]
w2: [[-1.69176853]
 [ 2.53856683]
 [ 1.2484405 ]]


w1: [[-1.82371032  2.45222616  1.50664747]
 [-3.32359076  0.93434495  1.9319154 ]]
w2: [[-1.69197023]
 [ 2.53879094]
 [ 1.24870682]]


w1: [[-1.82389832  2.45240307  1.50689447]
 [-3.32378936  0.93453056  1.93218303]]
w2: [[-1.692151

w1: [[-1.8363359   2.46411157  1.52318513]
 [-3.33692312  0.9468016   1.94978774]]
w2: [[-1.70415974]
 [ 2.55232406]
 [ 1.26475263]]


w1: [[-1.83657134  2.4643333   1.52349257]
 [-3.33717155  0.94703376  1.95011914]]
w2: [[-1.70438695]
 [ 2.5525763 ]
 [ 1.26505065]]


w1: [[-1.83678341  2.46453285  1.52376938]
 [-3.33739519  0.9472428   1.95041752]]
w2: [[-1.70459151]
 [ 2.55280328]
 [ 1.26531911]]


w1: [[-1.83697438  2.46471262  1.52401865]
 [-3.33759665  0.94743103  1.95068622]]
w2: [[-1.70477581]
 [ 2.55300784]
 [ 1.26556075]]


w1: [[-1.83714628  2.46487451  1.52424312]
 [-3.33777809  0.94760054  1.95092821]]
w2: [[-1.70494175]
 [ 2.5531919 ]
 [ 1.26577842]]


w1: [[-1.83730114  2.46502018  1.52444518]
 [-3.33794141  0.94775319  1.95114613]]
w2: [[-1.70509112]
 [ 2.5533576 ]
 [ 1.2659744 ]]


w1: [[-1.83744049  2.46515131  1.52462721]
 [-3.33808851  0.94789064  1.95134234]]
w2: [[-1.70522559]
 [ 2.55350685]
 [ 1.26615083]]


w1: [[-1.83756602  2.46526957  1.52479112]
 [-3.3382208

w2: [[-1.71579206]
 [ 2.56522846]
 [ 1.27996874]]


w1: [[-1.84849024  2.47555232  1.53900576]
 [-3.34973407  0.95877695  1.96680713]]
w2: [[-1.71588147]
 [ 2.56532764]
 [ 1.28008544]]


w1: [[-1.8485738   2.475631    1.53911424]
 [-3.34982204  0.95885921  1.96692359]]
w2: [[-1.71596193]
 [ 2.56541705]
 [ 1.28019047]]


w1: [[-1.84864902  2.47570181  1.53921187]
 [-3.3499012   0.95893329  1.9670285 ]]
w2: [[-1.71603441]
 [ 2.5654974 ]
 [ 1.28028512]]


w1: [[-1.84871674  2.47576547  1.53929985]
 [-3.34997249  0.95899999  1.96712291]]
w2: [[-1.71609974]
 [ 2.56556988]
 [ 1.28037035]]


w1: [[-1.8490442   2.47607374  1.53972435]
 [-3.35031724  0.95932233  1.96757841]]
w2: [[-1.71641529]
 [ 2.56591988]
 [ 1.28078151]]


w1: [[-1.84933901  2.47635126  1.54010665]
 [-3.35062766  0.95961261  1.96798861]]
w2: [[-1.71669948]
 [ 2.56623483]
 [ 1.28115177]]


w1: [[-1.84960449  2.47660112  1.54045093]
 [-3.35090709  0.95987397  1.96835792]]
w2: [[-1.7169553 ]
 [ 2.56651855]
 [ 1.2814852 ]]


w1:

w2: [[-1.72776115]
 [ 2.5784936 ]
 [ 1.29552937]]


w1: [[-1.86101723  2.48734641  1.55520892]
 [-3.36291456  0.9711042   1.98416352]]
w2: [[-1.72794998]
 [ 2.57870269]
 [ 1.2957741 ]]


w1: [[-1.86119378  2.48751259  1.55543661]
 [-3.36310029  0.97127789  1.98440695]]
w2: [[-1.72811997]
 [ 2.57889104]
 [ 1.29599452]]


w1: [[-1.8613528   2.48766232  1.55564165]
 [-3.36326742  0.9714343   1.98462617]]
w2: [[-1.72827303]
 [ 2.57906055]
 [ 1.296193  ]]


w1: [[-1.86149597  2.48779702  1.55582631]
 [-3.36341786  0.97157508  1.98482358]]
w2: [[-1.72841096]
 [ 2.57921338]
 [ 1.2963717 ]]


w1: [[-1.86162496  2.48791838  1.5559926 ]
 [-3.36355329  0.97170186  1.98500133]]
w2: [[-1.72853506]
 [ 2.57935095]
 [ 1.29653263]]


w1: [[-1.86174107  2.48802757  1.55614233]
 [-3.36367536  0.971816    1.98516142]]
w2: [[-1.72864687]
 [ 2.57947469]
 [ 1.29667747]]


w1: [[-1.86184561  2.48812604  1.55627716]
 [-3.36378527  0.97191882  1.98530555]]
w2: [[-1.72874749]
 [ 2.57958627]
 [ 1.29680789]]


w1:

w1: [[-1.88117945  2.50633216  1.58107567]
 [-3.38407707  0.99091303  2.01172733]]
w2: [[-1.74734926]
 [ 2.60017681]
 [ 1.32078898]]


w1: [[-1.8812573   2.50640535  1.58117509]
 [-3.38415861  0.99098945  2.01183295]]
w2: [[-1.74742413]
 [ 2.60025954]
 [ 1.32088506]]


w1: [[-1.88132739  2.5064714   1.58126462]
 [-3.38423204  0.99105823  2.01192808]]
w2: [[-1.74749148]
 [ 2.60033417]
 [ 1.32097161]]


w1: [[-1.88166606  2.5067904   1.58169663]
 [-3.38458705  0.99139065  2.0123868 ]]
w2: [[-1.74781716]
 [ 2.60069442]
 [ 1.32138908]]


w1: [[-1.881971    2.50707769  1.58208561]
 [-3.38490677  0.99168998  2.01279974]]
w2: [[-1.74811041]
 [ 2.60101867]
 [ 1.32176507]]


w1: [[-1.88224566  2.50733638  1.58243585]
 [-3.38519454  0.99195951  2.01317167]]
w2: [[-1.74837446]
 [ 2.60131073]
 [ 1.32210362]]


w1: [[-1.8824929   2.50756931  1.58275127]
 [-3.3854537   0.99220222  2.01350665]]
w2: [[-1.74861217]
 [ 2.60157371]
 [ 1.32240844]]


w1: [[-1.88271558  2.50777912  1.58303523]
 [-3.3856871



w1: [[-1.8968457   2.5210886   1.60099471]
 [-3.40048003  1.00627947  2.03284049]]
w2: [[-1.76240396]
 [ 2.61681771]
 [ 1.34003186]]


w1: [[-1.89702868  2.52126098  1.60122645]
 [-3.40067148  1.00645876  2.03308558]]
w2: [[-1.76257968]
 [ 2.61701179]
 [ 1.34025562]]


w1: [[-1.89719343  2.52141619  1.60143507]
 [-3.40084386  1.00662029  2.03330636]]
w2: [[-1.76273787]
 [ 2.61718655]
 [ 1.34045708]]


w1: [[-1.89734173  2.5215559   1.60162294]
 [-3.40099907  1.00676572  2.0335052 ]]
w2: [[-1.76288033]
 [ 2.6173439 ]
 [ 1.34063852]]


w1: [[-1.89747524  2.52168179  1.6017921 ]
 [-3.40113878  1.00689662  2.03368425]]
w2: [[-1.76300859]
 [ 2.61748552]
 [ 1.34080195]]


w1: [[-1.89759552  2.52179503  1.60194445]
 [-3.40126467  1.00701451  2.03384542]]
w2: [[-1.76312411]
 [ 2.61761308]
 [ 1.34094906]]


w1: [[-1.89770377  2.52189708  1.60208166]
 [-3.40137792  1.00712073  2.03399062]]
w2: [[-1.76322818]
 [ 2.61772799]
 [ 1.3410815 ]]


w1: [[-1.89780128  2.52198887  1.60220516]
 [-3.40147

w1: [[-1.9117142   2.53509855  1.61975992]
 [-3.41601729  1.02084601  2.05264902]]
w2: [[-1.77668023]
 [ 2.63257861]
 [ 1.35814667]]


w1: [[-1.91182387  2.53520179  1.61989784]
 [-3.41613173  1.02095342  2.05279446]]
w2: [[-1.77678549]
 [ 2.63269472]
 [ 1.35827982]]


w1: [[-1.91192257  2.53529477  1.62002206]
 [-3.41623473  1.0210501   2.05292535]]
w2: [[-1.77688026]
 [ 2.63279939]
 [ 1.35839975]]


w1: [[-1.9120115   2.53537846  1.62013388]
 [-3.41632748  1.02113712  2.05304313]]
w2: [[-1.77696562]
 [ 2.63289356]
 [ 1.35850775]]


w1: [[-1.91209161  2.5354538   1.62023461]
 [-3.41641116  1.02121556  2.05314922]]
w2: [[-1.77704251]
 [ 2.63297844]
 [ 1.35860491]]


w1: [[-1.91216373  2.53552175  1.62032533]
 [-3.4164865   1.02128613  2.05324483]]
w2: [[-1.77711165]
 [ 2.63305473]
 [ 1.35869241]]


w1: [[-1.91251218  2.53585005  1.62076306]
 [-3.41685009  1.02162719  2.05370569]]
w2: [[-1.77744603]
 [ 2.63342357]
 [ 1.35911477]]


w1: [[-1.91282594  2.53614569  1.62115717]
 [-3.4171774

 [-3.43290591  1.03669178  2.07397938]]
w2: [[-1.79221523]
 [ 2.64970756]
 [ 1.37771571]]


w1: [[-1.92811704  2.55055881  1.64030564]
 [-3.43312335  1.03689587  2.07425284]]
w2: [[-1.79241538]
 [ 2.64992809]
 [ 1.37796688]]


w1: [[-1.92830503  2.55073595  1.64054012]
 [-3.43331909  1.03707969  2.07449889]]
w2: [[-1.79259562]
 [ 2.6501267 ]
 [ 1.37819302]]


w1: [[-1.92847431  2.55089545  1.64075136]
 [-3.43349552  1.03724515  2.07472062]]
w2: [[-1.79275787]
 [ 2.65030551]
 [ 1.37839675]]


w1: [[-1.92862666  2.55103922  1.6409415 ]
 [-3.43365431  1.03739417  2.07492018]]
w2: [[-1.79290402]
 [ 2.65046644]
 [ 1.37858009]]


w1: [[-1.92876387  2.55116868  1.64111269]
 [-3.43379736  1.0375284   2.07509995]]
w2: [[-1.79303563]
 [ 2.6506114 ]
 [ 1.3787452 ]]


w1: [[-1.92888749  2.55128527  1.64126682]
 [-3.43392611  1.03764927  2.07526183]]
w2: [[-1.79315412]
 [ 2.65074205]
 [ 1.37889385]]


w1: [[-1.92899871  2.55139017  1.6414057 ]
 [-3.43404198  1.03775811  2.07540751]]
w2: [[-1.793260

w2: [[-1.80462933]
 [ 2.66337919]
 [ 1.39325035]]


w1: [[-1.94093251  2.56264257  1.65624774]
 [-3.4464643   1.04942238  2.09096003]]
w2: [[-1.80470014]
 [ 2.66345716]
 [ 1.39333868]]


w1: [[-1.94128919  2.56297898  1.65668976]
 [-3.44683528  1.04977083  2.09142256]]
w2: [[-1.80504191]
 [ 2.66383338]
 [ 1.39376485]]


w1: [[-1.94161034  2.56328201  1.6570878 ]
 [-3.4471693   1.05008459  2.09183908]]
w2: [[-1.80534971]
 [ 2.66417217]
 [ 1.39414859]]


w1: [[-1.94189954  2.56355476  1.65744627]
 [-3.44747019  1.05036712  2.09221411]]
w2: [[-1.80562687]
 [ 2.66447711]
 [ 1.39449418]]


w1: [[-1.94216001  2.56380033  1.65776908]
 [-3.44774103  1.05062151  2.09255171]]
w2: [[-1.80587637]
 [ 2.66475177]
 [ 1.39480531]]


w1: [[-1.9423945   2.56402159  1.65805972]
 [-3.44798493  1.05085063  2.09285569]]
w2: [[-1.80610108]
 [ 2.66499901]
 [ 1.39508545]]


w1: [[-1.94260561  2.56422067  1.65832138]
 [-3.44820452  1.05105686  2.0931294 ]]
w2: [[-1.80630338]
 [ 2.66522169]
 [ 1.3953377 ]]


w1:

w1: [[-1.95549202  2.57637644  1.67424417]
 [-3.46159601  1.06364024  2.1097641 ]]
w2: [[-1.81864822]
 [ 2.67879963]
 [ 1.41068494]]


w1: [[-1.95556664  2.57644677  1.67433619]
 [-3.4616735   1.06371307  2.10986018]]
w2: [[-1.81871974]
 [ 2.67887831]
 [ 1.41077363]]


w1: [[-1.95592725  2.57678699  1.67478013]
 [-3.46204782  1.0640651   2.11032319]]
w2: [[-1.81906509]
 [ 2.67925787]
 [ 1.41120148]]


w1: [[-1.95625198  2.57709336  1.67517996]
 [-3.46238494  1.06438208  2.11074018]]
w2: [[-1.81937611]
 [ 2.67959976]
 [ 1.41158676]]


w1: [[-1.9565444   2.57736921  1.67553997]
 [-3.46268845  1.06466746  2.11111569]]
w2: [[-1.81965613]
 [ 2.67990756]
 [ 1.41193366]]


w1: [[-1.95680773  2.57761765  1.6758641 ]
 [-3.46296191  1.06492448  2.11145377]]
w2: [[-1.81990826]
 [ 2.6801846 ]
 [ 1.41224599]]


w1: [[-1.95704484  2.57784128  1.67615604]
 [-3.46320796  1.06515586  2.11175823]]
w2: [[-1.82013535]
 [ 2.68043423]
 [ 1.41252732]]


w1: [[-1.95725834  2.57804275  1.6764189 ]
 [-3.4634296