In [1]:
import tensorflow as tf

# The file path to save the data
# 文件保存路径
save_file = './model.ckpt'
# Remove the previous weights and bias
# 移除之前的权重和偏置项
tf.reset_default_graph()

# Two Variables: weights and bias
# 两个变量：权重和偏置项
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
# 用来存取 Tensor 变量的类
saver = tf.train.Saver()

with tf.Session() as sess:
    # Load the weights and bias
    # 加载权重和偏置项
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    # 显示权重和偏置项
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from ./model.ckpt
Weight:
[[-0.29686347 -0.15109432 -0.31330508]
 [-0.23756455 -0.3111253   1.275599  ]]
Bias:
[-0.49002755 -1.0292462   1.034822  ]


In [2]:
import tensorflow as tf

# The file path to save the data
# 文件保存路径
save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
# 两个 Tensor 变量：权重和偏置项
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
# 用来存取 Tensor 变量的类
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    # 初始化所有变量
    sess.run(tf.global_variables_initializer())

    # Show the values of weights and bias
   # 显示变量和权重
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    # 保存模型
    saver.save(sess, save_file)

Weights:
[[-1.6831803  -0.78130925  0.13813882]
 [-0.10859775 -0.7265929  -0.09383129]]
Bias:
[-0.00260877 -0.4270929  -0.9221714 ]


In [3]:
# Remove previous Tensors and Operations
# 移除之前的  Tensors 和运算
tf.reset_default_graph()

In [4]:
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

learning_rate = 0.001
n_input = 784  # MNIST 数据输入 (图片尺寸: 28*28)
n_classes = 10  # MNIST 总计类别 (数字 0-9)

# Import MNIST data
# 加载 MNIST 数据
# mnist = input_data.read_data_sets('.', one_hot=True)
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)


# Features and Labels
# 特征和标签
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
# 权重和偏置项
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
# 定义损失函数和优化器
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
# 计算准确率
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.



In [5]:
import math

save_file = './train_model.ckpt'
batch_size = 128
n_epochs = 100

saver = tf.train.Saver()

# Launch the graph
# 启动图
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # Training cycle
    # 训练循环
    for epoch in range(n_epochs):
        total_batch = math.ceil(mnist.train.num_examples / batch_size)

        # Loop over all batches
        # 遍历所有 batch
        for i in range(total_batch):
            batch_features, batch_labels = mnist.train.next_batch(batch_size)
            sess.run(
                optimizer,
                feed_dict={features: batch_features, labels: batch_labels})

        # Print status for every 10 epochs
        # 每运行10个 epoch 打印一次状态
        if epoch % 10 == 0:
            valid_accuracy = sess.run(
                accuracy,
                feed_dict={
                    features: mnist.validation.images,
                    labels: mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy: {}'.format(
                epoch,
                valid_accuracy))

    # Save the model
    # 保存模型
    saver.save(sess, save_file)
    print('Trained Model Saved.')

Epoch 0   - Validation Accuracy: 0.14000000059604645
Epoch 10  - Validation Accuracy: 0.27799999713897705
Epoch 20  - Validation Accuracy: 0.40400001406669617
Epoch 30  - Validation Accuracy: 0.5034000277519226
Epoch 40  - Validation Accuracy: 0.5631999969482422
Epoch 50  - Validation Accuracy: 0.6096000075340271
Epoch 60  - Validation Accuracy: 0.642799973487854
Epoch 70  - Validation Accuracy: 0.6697999835014343
Epoch 80  - Validation Accuracy: 0.6891999840736389
Epoch 90  - Validation Accuracy: 0.7075999975204468
Trained Model Saved.


In [6]:
saver = tf.train.Saver()

# Launch the graph
# 加载图
with tf.Session() as sess:
    saver.restore(sess, save_file)

    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: mnist.test.images, labels: mnist.test.labels})

print('Test Accuracy: {}'.format(test_accuracy))

INFO:tensorflow:Restoring parameters from ./train_model.ckpt
Test Accuracy: 0.7174999713897705


In [14]:
import tensorflow as tf
tf.reset_default_graph()
save_file = './model2.ckpt'
# bias weights
weights = tf.Variable(tf.truncated_normal([2,3]), name='w1')
bias = tf.Variable(tf.truncated_normal([3]), name='b1')

# saver
saver = tf.train.Saver()

print('Save Weight:{}'.format(weights.name))
print('Save Bias:{}'.format(bias.name))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess, save_file)

# 移除之前的权重和偏置项
tf.reset_default_graph()

bias = tf.Variable(tf.truncated_normal([3]), name='b1')
weights = tf.Variable(tf.truncated_normal([2,3]), name='w1')

saver2 = tf.train.Saver()
# 打印权重和偏置项的名称
print('Save Weight:{}'.format(weights.name))
print('Save Bias:{}'.format(bias.name))

with tf.Session() as sess:
    # 加载权重和偏置项
    saver.restore(sess, save_file)

Save Weight:w1:0
Save Bias:b1:0
Save Weight:w1:0
Save Bias:b1:0
INFO:tensorflow:Restoring parameters from ./model2.ckpt
